// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientGetFriendLeaderboard.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientGetFriendLeaderboard::UPFClientGetFriendLeaderboard(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetFriendLeaderboardDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientGetFriendLeaderboard* UPFClientGetFriendLeaderboard::GetFriendLeaderboard(class APlayerController* PlayerController, const FBPClientGetFriendLeaderboardRequest& InGetFriendLeaderboardRequest)
{
    UPFClientGetFriendLeaderboard* Proxy = NewObject<UPFClientGetFriendLeaderboard>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetFriendLeaderboardRequest;
    
    return Proxy;
}

void UPFClientGetFriendLeaderboard::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->GetFriendLeaderboard(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientGetFriendLeaderboard::OnSuccessCallback(const PlayFab::ClientModels::FGetLeaderboardResult& Result)
{
    FBPClientGetLeaderboardResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
