// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientUnlinkKongregate.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientUnlinkKongregate::UPFClientUnlinkKongregate(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FUnlinkKongregateDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientUnlinkKongregate* UPFClientUnlinkKongregate::UnlinkKongregate(class APlayerController* PlayerController)
{
    UPFClientUnlinkKongregate* Proxy = NewObject<UPFClientUnlinkKongregate>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    
    return Proxy;
}

void UPFClientUnlinkKongregate::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->UnlinkKongregate(SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientUnlinkKongregate::OnSuccessCallback(const PlayFab::ClientModels::FUnlinkKongregateAccountResult& Result)
{
    OnSuccess.Broadcast();
}
