// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientGetUserPublisherData.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientGetUserPublisherData::UPFClientGetUserPublisherData(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetUserPublisherDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientGetUserPublisherData* UPFClientGetUserPublisherData::GetUserPublisherData(class APlayerController* PlayerController, const FBPClientGetUserDataRequest& InGetUserDataRequest)
{
    UPFClientGetUserPublisherData* Proxy = NewObject<UPFClientGetUserPublisherData>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetUserDataRequest;
    
    return Proxy;
}

void UPFClientGetUserPublisherData::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if (ClientAPI.IsValid())
    {
        CallResult = ClientAPI->GetUserPublisherData(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFClientGetUserPublisherData::OnSuccessCallback(const PlayFab::ClientModels::FGetUserDataResult& Result)
{
    FBPClientGetUserDataResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
