// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientAttributeInstall.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientAttributeInstall::UPFClientAttributeInstall(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FAttributeInstallDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientAttributeInstall* UPFClientAttributeInstall::AttributeInstall(class APlayerController* PlayerController, const FBPClientAttributeInstallRequest& InAttributeInstallRequest)
{
    UPFClientAttributeInstall* Proxy = NewObject<UPFClientAttributeInstall>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InAttributeInstallRequest;
    
    return Proxy;
}

void UPFClientAttributeInstall::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->AttributeInstall(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientAttributeInstall::OnSuccessCallback(const PlayFab::ClientModels::FAttributeInstallResult& Result)
{
    OnSuccess.Broadcast();
}
