// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientPurchaseItem.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientPurchaseItem::UPFClientPurchaseItem(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FPurchaseItemDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientPurchaseItem* UPFClientPurchaseItem::PurchaseItem(class APlayerController* PlayerController, const FBPClientPurchaseItemRequest& InPurchaseItemRequest)
{
    UPFClientPurchaseItem* Proxy = NewObject<UPFClientPurchaseItem>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InPurchaseItemRequest;
    
    return Proxy;
}

void UPFClientPurchaseItem::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->PurchaseItem(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientPurchaseItem::OnSuccessCallback(const PlayFab::ClientModels::FPurchaseItemResult& Result)
{
    FBPClientPurchaseItemResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
