// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientGetWindowsHelloChallenge.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientGetWindowsHelloChallenge::UPFClientGetWindowsHelloChallenge(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetWindowsHelloChallengeDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientGetWindowsHelloChallenge* UPFClientGetWindowsHelloChallenge::GetWindowsHelloChallenge(class APlayerController* PlayerController, const FBPClientGetWindowsHelloChallengeRequest& InGetWindowsHelloChallengeRequest)
{
    UPFClientGetWindowsHelloChallenge* Proxy = NewObject<UPFClientGetWindowsHelloChallenge>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetWindowsHelloChallengeRequest;
    
    return Proxy;
}

void UPFClientGetWindowsHelloChallenge::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->GetWindowsHelloChallenge(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientGetWindowsHelloChallenge::OnSuccessCallback(const PlayFab::ClientModels::FGetWindowsHelloChallengeResponse& Result)
{
    FBPClientGetWindowsHelloChallengeResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
