// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientAndroidDevicePushNotificationRegistration.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientAndroidDevicePushNotificationRegistration::UPFClientAndroidDevicePushNotificationRegistration(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FAndroidDevicePushNotificationRegistrationDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientAndroidDevicePushNotificationRegistration* UPFClientAndroidDevicePushNotificationRegistration::AndroidDevicePushNotificationRegistration(class APlayerController* PlayerController, const FBPClientAndroidDevicePushNotificationRegistrationRequest& InAndroidDevicePushNotificationRegistrationRequest)
{
    UPFClientAndroidDevicePushNotificationRegistration* Proxy = NewObject<UPFClientAndroidDevicePushNotificationRegistration>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InAndroidDevicePushNotificationRegistrationRequest;
    
    return Proxy;
}

void UPFClientAndroidDevicePushNotificationRegistration::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->AndroidDevicePushNotificationRegistration(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientAndroidDevicePushNotificationRegistration::OnSuccessCallback(const PlayFab::ClientModels::FAndroidDevicePushNotificationRegistrationResult& Result)
{
    OnSuccess.Broadcast();
}
