// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientGetPlayFabIDsFromGameCenterIDs.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientGetPlayFabIDsFromGameCenterIDs::UPFClientGetPlayFabIDsFromGameCenterIDs(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetPlayFabIDsFromGameCenterIDsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientGetPlayFabIDsFromGameCenterIDs* UPFClientGetPlayFabIDsFromGameCenterIDs::GetPlayFabIDsFromGameCenterIDs(class APlayerController* PlayerController, const FBPClientGetPlayFabIDsFromGameCenterIDsRequest& InGetPlayFabIDsFromGameCenterIDsRequest)
{
    UPFClientGetPlayFabIDsFromGameCenterIDs* Proxy = NewObject<UPFClientGetPlayFabIDsFromGameCenterIDs>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetPlayFabIDsFromGameCenterIDsRequest;
    
    return Proxy;
}

void UPFClientGetPlayFabIDsFromGameCenterIDs::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->GetPlayFabIDsFromGameCenterIDs(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientGetPlayFabIDsFromGameCenterIDs::OnSuccessCallback(const PlayFab::ClientModels::FGetPlayFabIDsFromGameCenterIDsResult& Result)
{
    FBPClientGetPlayFabIDsFromGameCenterIDsResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
