// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientGetPlayFabIDsFromGoogleIDs.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientGetPlayFabIDsFromGoogleIDs::UPFClientGetPlayFabIDsFromGoogleIDs(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetPlayFabIDsFromGoogleIDsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientGetPlayFabIDsFromGoogleIDs* UPFClientGetPlayFabIDsFromGoogleIDs::GetPlayFabIDsFromGoogleIDs(class APlayerController* PlayerController, const FBPClientGetPlayFabIDsFromGoogleIDsRequest& InGetPlayFabIDsFromGoogleIDsRequest)
{
    UPFClientGetPlayFabIDsFromGoogleIDs* Proxy = NewObject<UPFClientGetPlayFabIDsFromGoogleIDs>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetPlayFabIDsFromGoogleIDsRequest;
    
    return Proxy;
}

void UPFClientGetPlayFabIDsFromGoogleIDs::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->GetPlayFabIDsFromGoogleIDs(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientGetPlayFabIDsFromGoogleIDs::OnSuccessCallback(const PlayFab::ClientModels::FGetPlayFabIDsFromGoogleIDsResult& Result)
{
    FBPClientGetPlayFabIDsFromGoogleIDsResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
