// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientLoginWithFacebook.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientLoginWithFacebook::UPFClientLoginWithFacebook(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FLoginWithFacebookDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientLoginWithFacebook* UPFClientLoginWithFacebook::LoginWithFacebook(class APlayerController* PlayerController, const FBPClientLoginWithFacebookRequest& InLoginWithFacebookRequest)
{
    UPFClientLoginWithFacebook* Proxy = NewObject<UPFClientLoginWithFacebook>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InLoginWithFacebookRequest;
    
    return Proxy;
}

void UPFClientLoginWithFacebook::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->LoginWithFacebook(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientLoginWithFacebook::OnSuccessCallback(const PlayFab::ClientModels::FLoginResult& Result)
{
    FBPClientLoginResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
