// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminUpdateUserPublisherInternalData.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminUpdateUserPublisherInternalData::UPFAdminUpdateUserPublisherInternalData(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FUpdateUserPublisherInternalDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminUpdateUserPublisherInternalData* UPFAdminUpdateUserPublisherInternalData::UpdateUserPublisherInternalData(class APlayerController* PlayerController, const FBPAdminUpdateUserInternalDataRequest& InUpdateUserInternalDataRequest)
{
    UPFAdminUpdateUserPublisherInternalData* Proxy = NewObject<UPFAdminUpdateUserPublisherInternalData>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InUpdateUserInternalDataRequest;
    
    return Proxy;
}

void UPFAdminUpdateUserPublisherInternalData::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if (AdminAPI.IsValid())
    {
        CallResult = AdminAPI->UpdateUserPublisherInternalData(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFAdminUpdateUserPublisherInternalData::OnSuccessCallback(const PlayFab::AdminModels::FUpdateUserDataResult& Result)
{
    FBPAdminUpdateUserDataResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
