// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminSetPublisherData.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminSetPublisherData::UPFAdminSetPublisherData(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FSetPublisherDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminSetPublisherData* UPFAdminSetPublisherData::SetPublisherData(class APlayerController* PlayerController, const FBPAdminSetPublisherDataRequest& InSetPublisherDataRequest)
{
    UPFAdminSetPublisherData* Proxy = NewObject<UPFAdminSetPublisherData>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InSetPublisherDataRequest;
    
    return Proxy;
}

void UPFAdminSetPublisherData::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if(AdminAPI.IsValid())
    {
        CallResult = AdminAPI->SetPublisherData(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFAdminSetPublisherData::OnSuccessCallback(const PlayFab::AdminModels::FSetPublisherDataResult& Result)
{
    OnSuccess.Broadcast();
}
