// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminAddVirtualCurrencyTypes.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminAddVirtualCurrencyTypes::UPFAdminAddVirtualCurrencyTypes(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FAddVirtualCurrencyTypesDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminAddVirtualCurrencyTypes* UPFAdminAddVirtualCurrencyTypes::AddVirtualCurrencyTypes(class APlayerController* PlayerController, const FBPAdminAddVirtualCurrencyTypesRequest& InAddVirtualCurrencyTypesRequest)
{
    UPFAdminAddVirtualCurrencyTypes* Proxy = NewObject<UPFAdminAddVirtualCurrencyTypes>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InAddVirtualCurrencyTypesRequest;
    
    return Proxy;
}

void UPFAdminAddVirtualCurrencyTypes::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if(AdminAPI.IsValid())
    {
        CallResult = AdminAPI->AddVirtualCurrencyTypes(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFAdminAddVirtualCurrencyTypes::OnSuccessCallback(const PlayFab::AdminModels::FBlankResult& Result)
{
    OnSuccess.Broadcast();
}
