// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminSetupPushNotification.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminSetupPushNotification::UPFAdminSetupPushNotification(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FSetupPushNotificationDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminSetupPushNotification* UPFAdminSetupPushNotification::SetupPushNotification(class APlayerController* PlayerController, const FBPAdminSetupPushNotificationRequest& InSetupPushNotificationRequest)
{
    UPFAdminSetupPushNotification* Proxy = NewObject<UPFAdminSetupPushNotification>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InSetupPushNotificationRequest;
    
    return Proxy;
}

void UPFAdminSetupPushNotification::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if (AdminAPI.IsValid())
    {
        CallResult = AdminAPI->SetupPushNotification(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFAdminSetupPushNotification::OnSuccessCallback(const PlayFab::AdminModels::FSetupPushNotificationResult& Result)
{
    FBPAdminSetupPushNotificationResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
