// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminGetPlayerTags.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminGetPlayerTags::UPFAdminGetPlayerTags(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FGetPlayerTagsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminGetPlayerTags* UPFAdminGetPlayerTags::GetPlayerTags(class APlayerController* PlayerController, const FBPAdminGetPlayerTagsRequest& InGetPlayerTagsRequest)
{
    UPFAdminGetPlayerTags* Proxy = NewObject<UPFAdminGetPlayerTags>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetPlayerTagsRequest;
    
    return Proxy;
}

void UPFAdminGetPlayerTags::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if (AdminAPI.IsValid())
    {
        CallResult = AdminAPI->GetPlayerTags(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFAdminGetPlayerTags::OnSuccessCallback(const PlayFab::AdminModels::FGetPlayerTagsResult& Result)
{
    FBPAdminGetPlayerTagsResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
