// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminAddServerBuild.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminAddServerBuild::UPFAdminAddServerBuild(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FAddServerBuildDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminAddServerBuild* UPFAdminAddServerBuild::AddServerBuild(class APlayerController* PlayerController, const FBPAdminAddServerBuildRequest& InAddServerBuildRequest)
{
    UPFAdminAddServerBuild* Proxy = NewObject<UPFAdminAddServerBuild>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InAddServerBuildRequest;
    
    return Proxy;
}

void UPFAdminAddServerBuild::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if(AdminAPI.IsValid())
    {
        CallResult = AdminAPI->AddServerBuild(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFAdminAddServerBuild::OnSuccessCallback(const PlayFab::AdminModels::FAddServerBuildResult& Result)
{
    FBPAdminAddServerBuildResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
