// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminGetCloudScriptRevision.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminGetCloudScriptRevision::UPFAdminGetCloudScriptRevision(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FGetCloudScriptRevisionDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminGetCloudScriptRevision* UPFAdminGetCloudScriptRevision::GetCloudScriptRevision(class APlayerController* PlayerController, const FBPAdminGetCloudScriptRevisionRequest& InGetCloudScriptRevisionRequest)
{
    UPFAdminGetCloudScriptRevision* Proxy = NewObject<UPFAdminGetCloudScriptRevision>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetCloudScriptRevisionRequest;
    
    return Proxy;
}

void UPFAdminGetCloudScriptRevision::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if (AdminAPI.IsValid())
    {
        CallResult = AdminAPI->GetCloudScriptRevision(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFAdminGetCloudScriptRevision::OnSuccessCallback(const PlayFab::AdminModels::FGetCloudScriptRevisionResult& Result)
{
    FBPAdminGetCloudScriptRevisionResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
