// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminModifyMatchmakerGameModes.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminModifyMatchmakerGameModes::UPFAdminModifyMatchmakerGameModes(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FModifyMatchmakerGameModesDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminModifyMatchmakerGameModes* UPFAdminModifyMatchmakerGameModes::ModifyMatchmakerGameModes(class APlayerController* PlayerController, const FBPAdminModifyMatchmakerGameModesRequest& InModifyMatchmakerGameModesRequest)
{
    UPFAdminModifyMatchmakerGameModes* Proxy = NewObject<UPFAdminModifyMatchmakerGameModes>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InModifyMatchmakerGameModesRequest;
    
    return Proxy;
}

void UPFAdminModifyMatchmakerGameModes::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if(AdminAPI.IsValid())
    {
        CallResult = AdminAPI->ModifyMatchmakerGameModes(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFAdminModifyMatchmakerGameModes::OnSuccessCallback(const PlayFab::AdminModels::FModifyMatchmakerGameModesResult& Result)
{
    OnSuccess.Broadcast();
}
