// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFClientUnlinkWindowsHello.h"

UPFClientUnlinkWindowsHello::UPFClientUnlinkWindowsHello(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FUnlinkWindowsHelloDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientUnlinkWindowsHello* UPFClientUnlinkWindowsHello::UnlinkWindowsHello(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPublicKeyHint)
{
	UPFClientUnlinkWindowsHello* Proxy = NewObject<UPFClientUnlinkWindowsHello>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PublicKeyHint = InPublicKeyHint;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientUnlinkWindowsHello::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->UnlinkWindowsHello(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		OnFailure.Broadcast();
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientUnlinkWindowsHello::OnSuccessCallback(const PlayFab::ClientModels::FUnlinkWindowsHelloAccountResponse& Result)
{
	OnSuccess.Broadcast();
}

void UPFClientUnlinkWindowsHello::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	OnFailure.Broadcast();	
}
