// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFClientSetPlayerSecret.h"

UPFClientSetPlayerSecret::UPFClientSetPlayerSecret(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabClientAPI::FSetPlayerSecretDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFClientSetPlayerSecret* UPFClientSetPlayerSecret::SetPlayerSecret(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPlayerSecret, const FString& InEncryptedRequest)
{
	UPFClientSetPlayerSecret* Proxy = NewObject<UPFClientSetPlayerSecret>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PlayerSecret = InPlayerSecret;
	Proxy->Request.EncryptedRequest = InEncryptedRequest;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFClientSetPlayerSecret::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

	bool CallResult = false;

	if(ClientAPI.IsValid())
	{	
		CallResult = ClientAPI->SetPlayerSecret(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		OnFailure.Broadcast();
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFClientSetPlayerSecret::OnSuccessCallback(const PlayFab::ClientModels::FSetPlayerSecretResult& Result)
{
	OnSuccess.Broadcast();
}

void UPFClientSetPlayerSecret::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	OnFailure.Broadcast();	
}
