// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabMatchmakerAPI.h"
#include "Core/PlayFabMatchmakerDataModels.h"
#include "Proxy/PlayFabMatchmakerBPDataModels.h"
#include "PFMatchmakerPlayerJoined.generated.h"

UCLASS(MinimalAPI)
class UPFMatchmakerPlayerJoined : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Informs the PlayFab game server hosting service that the indicated user has joined the Game Server Instance specified
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Matchmaker|Matchmaking")
        static UPFMatchmakerPlayerJoined* PlayerJoined(class APlayerController* PlayerController, const FBPMatchmakerPlayerJoinedRequest& InPlayerJoinedRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPMatchmakerPlayerJoinedRequest Request;
    PlayFab::UPlayFabMatchmakerAPI::FPlayerJoinedDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::MatchmakerModels::FPlayerJoinedResponse& Result);
};
