// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetPlayerTrades.generated.h"

UCLASS(MinimalAPI)
class UPFClientGetPlayerTrades : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientGetPlayerTradesResponseDelegate OnSuccess;

    // Gets all trades the player has either opened or accepted, optionally filtered by trade status.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Trading")
        static UPFClientGetPlayerTrades* GetPlayerTrades(class APlayerController* PlayerController, const FBPClientGetPlayerTradesRequest& InGetPlayerTradesRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientGetPlayerTradesRequest Request;
    PlayFab::UPlayFabClientAPI::FGetPlayerTradesDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FGetPlayerTradesResponse& Result);
};
