// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientReportDeviceInfo.generated.h"

UCLASS(MinimalAPI)
class UPFClientReportDeviceInfo : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Write a PlayStream event to describe the provided player device information. This API method is not designed to be called directly by developers. Each PlayFab client SDK will eventually report this information automatically.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Analytics")
        static UPFClientReportDeviceInfo* ReportDeviceInfo(class APlayerController* PlayerController, const FBPClientDeviceInfoRequest& InDeviceInfoRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientDeviceInfoRequest Request;
    PlayFab::UPlayFabClientAPI::FReportDeviceInfoDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FEmptyResult& Result);
};
