// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetTitleNews.generated.h"

UCLASS(MinimalAPI)
class UPFClientGetTitleNews : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientGetTitleNewsResultDelegate OnSuccess;

    // Retrieves the title news feed, as configured in the developer portal
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Title-Wide Data Management")
        static UPFClientGetTitleNews* GetTitleNews(class APlayerController* PlayerController, const FBPClientGetTitleNewsRequest& InGetTitleNewsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientGetTitleNewsRequest Request;
    PlayFab::UPlayFabClientAPI::FGetTitleNewsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FGetTitleNewsResult& Result);
};
