// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientCreateSharedGroup.generated.h"

UCLASS(MinimalAPI)
class UPFClientCreateSharedGroup : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientCreateSharedGroupResultDelegate OnSuccess;

    // Requests the creation of a shared group object, containing key/value pairs which may be updated by  all members of the group. Upon creation, the current user will be the only member of the group. Shared Groups are designed  for sharing data between a very small number of players, please see our guide: https://api.playfab.com/docs/tutorials/landing-players/shared-groups
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Shared Group Data")
        static UPFClientCreateSharedGroup* CreateSharedGroup(class APlayerController* PlayerController, const FBPClientCreateSharedGroupRequest& InCreateSharedGroupRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientCreateSharedGroupRequest Request;
    PlayFab::UPlayFabClientAPI::FCreateSharedGroupDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FCreateSharedGroupResult& Result);
};
