// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientPurchaseItem.generated.h"

UCLASS(MinimalAPI)
class UPFClientPurchaseItem : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientPurchaseItemResultDelegate OnSuccess;

    // Buys a single item with virtual currency. You must specify both the virtual currency to use to purchase,  as well as what the client believes the price to be. This lets the server fail the purchase if the price has changed.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Player Item Management")
        static UPFClientPurchaseItem* PurchaseItem(class APlayerController* PlayerController, const FBPClientPurchaseItemRequest& InPurchaseItemRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientPurchaseItemRequest Request;
    PlayFab::UPlayFabClientAPI::FPurchaseItemDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FPurchaseItemResult& Result);
};
