// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetCharacterLeaderboard.generated.h"

UCLASS(MinimalAPI)
class UPFClientGetCharacterLeaderboard : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientGetCharacterLeaderboardResultDelegate OnSuccess;

    // Retrieves a list of ranked characters for the given statistic, starting from the indicated point in the leaderboard
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Characters")
        static UPFClientGetCharacterLeaderboard* GetCharacterLeaderboard(class APlayerController* PlayerController, const FBPClientGetCharacterLeaderboardRequest& InGetCharacterLeaderboardRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientGetCharacterLeaderboardRequest Request;
    PlayFab::UPlayFabClientAPI::FGetCharacterLeaderboardDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FGetCharacterLeaderboardResult& Result);
};
