// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetUserInventory.generated.h"

UCLASS(MinimalAPI)
class UPFClientGetUserInventory : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientGetUserInventoryResultDelegate OnSuccess;

    // Retrieves the user's current inventory of virtual goods
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Player Item Management")
        static UPFClientGetUserInventory* GetUserInventory(class APlayerController* PlayerController);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    
    PlayFab::UPlayFabClientAPI::FGetUserInventoryDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FGetUserInventoryResult& Result);
};
