// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientValidateGooglePlayPurchase.generated.h"

UCLASS(MinimalAPI)
class UPFClientValidateGooglePlayPurchase : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Validates a Google Play purchase and gives the corresponding item to the player.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Platform Specific Methods")
        static UPFClientValidateGooglePlayPurchase* ValidateGooglePlayPurchase(class APlayerController* PlayerController, const FBPClientValidateGooglePlayPurchaseRequest& InValidateGooglePlayPurchaseRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientValidateGooglePlayPurchaseRequest Request;
    PlayFab::UPlayFabClientAPI::FValidateGooglePlayPurchaseDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FValidateGooglePlayPurchaseResult& Result);
};
