// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientSubtractUserVirtualCurrency.generated.h"

UCLASS(MinimalAPI)
class UPFClientSubtractUserVirtualCurrency : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientModifyUserVirtualCurrencyResultDelegate OnSuccess;

    // Decrements the user's balance of the specified virtual currency by the stated amount
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Player Item Management")
        static UPFClientSubtractUserVirtualCurrency* SubtractUserVirtualCurrency(class APlayerController* PlayerController, const FBPClientSubtractUserVirtualCurrencyRequest& InSubtractUserVirtualCurrencyRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientSubtractUserVirtualCurrencyRequest Request;
    PlayFab::UPlayFabClientAPI::FSubtractUserVirtualCurrencyDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FModifyUserVirtualCurrencyResult& Result);
};
