// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientWritePlayerEvent.generated.h"

UCLASS(MinimalAPI)
class UPFClientWritePlayerEvent : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientWriteEventResponseDelegate OnSuccess;

    // Writes a player-based event into PlayStream.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Analytics")
        static UPFClientWritePlayerEvent* WritePlayerEvent(class APlayerController* PlayerController, const FBPClientWriteClientPlayerEventRequest& InWriteClientPlayerEventRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientWriteClientPlayerEventRequest Request;
    PlayFab::UPlayFabClientAPI::FWritePlayerEventDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FWriteEventResponse& Result);
};
