// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetPlayFabIDsFromTwitchIDs.generated.h"

UCLASS(MinimalAPI)
class UPFClientGetPlayFabIDsFromTwitchIDs : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientGetPlayFabIDsFromTwitchIDsResultDelegate OnSuccess;

    // Retrieves the unique PlayFab identifiers for the given set of Twitch identifiers. The Twitch identifiers are the IDs for the user accounts, available as "_id" from the Twitch API methods (ex: https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md#get-usersuser).
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Account Management")
        static UPFClientGetPlayFabIDsFromTwitchIDs* GetPlayFabIDsFromTwitchIDs(class APlayerController* PlayerController, const FBPClientGetPlayFabIDsFromTwitchIDsRequest& InGetPlayFabIDsFromTwitchIDsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientGetPlayFabIDsFromTwitchIDsRequest Request;
    PlayFab::UPlayFabClientAPI::FGetPlayFabIDsFromTwitchIDsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FGetPlayFabIDsFromTwitchIDsResult& Result);
};
