// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientLinkCustomID.generated.h"

UCLASS(MinimalAPI)
class UPFClientLinkCustomID : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Links the custom identifier, generated by the title, to the user's PlayFab account
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Account Management")
        static UPFClientLinkCustomID* LinkCustomID(class APlayerController* PlayerController, const FBPClientLinkCustomIDRequest& InLinkCustomIDRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientLinkCustomIDRequest Request;
    PlayFab::UPlayFabClientAPI::FLinkCustomIDDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FLinkCustomIDResult& Result);
};
