// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientLoginWithAndroidDeviceID.generated.h"

UCLASS(MinimalAPI)
class UPFClientLoginWithAndroidDeviceID : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientLoginResultDelegate OnSuccess;

    // Signs the user in using the Android device identifier, returning a session identifier that can subsequently be used for API calls which require an authenticated user
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Authentication")
        static UPFClientLoginWithAndroidDeviceID* LoginWithAndroidDeviceID(class APlayerController* PlayerController, const FBPClientLoginWithAndroidDeviceIDRequest& InLoginWithAndroidDeviceIDRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientLoginWithAndroidDeviceIDRequest Request;
    PlayFab::UPlayFabClientAPI::FLoginWithAndroidDeviceIDDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FLoginResult& Result);
};
