// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetTitlePublicKey.generated.h"

UCLASS(MinimalAPI)
class UPFClientGetTitlePublicKey : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientGetTitlePublicKeyResultDelegate OnSuccess;

    // Returns the title's base 64 encoded RSA CSP blob.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Authentication")
        static UPFClientGetTitlePublicKey* GetTitlePublicKey(class APlayerController* PlayerController, const FBPClientGetTitlePublicKeyRequest& InGetTitlePublicKeyRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientGetTitlePublicKeyRequest Request;
    PlayFab::UPlayFabClientAPI::FGetTitlePublicKeyDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FGetTitlePublicKeyResult& Result);
};
