// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetPlayerStatisticVersions.generated.h"

UCLASS(MinimalAPI)
class UPFClientGetPlayerStatisticVersions : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientGetPlayerStatisticVersionsResultDelegate OnSuccess;

    // Retrieves the information on the available versions of the specified statistic.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Player Data Management")
        static UPFClientGetPlayerStatisticVersions* GetPlayerStatisticVersions(class APlayerController* PlayerController, const FBPClientGetPlayerStatisticVersionsRequest& InGetPlayerStatisticVersionsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientGetPlayerStatisticVersionsRequest Request;
    PlayFab::UPlayFabClientAPI::FGetPlayerStatisticVersionsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FGetPlayerStatisticVersionsResult& Result);
};
