// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetAllUsersCharacters.generated.h"

UCLASS(MinimalAPI)
class UPFClientGetAllUsersCharacters : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientListUsersCharactersResultDelegate OnSuccess;

    // Lists all of the characters that belong to a specific user. CharacterIds are not globally unique; characterId must be evaluated with the parent PlayFabId to guarantee uniqueness.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Characters")
        static UPFClientGetAllUsersCharacters* GetAllUsersCharacters(class APlayerController* PlayerController, const FBPClientListUsersCharactersRequest& InListUsersCharactersRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientListUsersCharactersRequest Request;
    PlayFab::UPlayFabClientAPI::FGetAllUsersCharactersDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FListUsersCharactersResult& Result);
};
