// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetPlayFabIDsFromKongregateIDs.generated.h"

UCLASS(MinimalAPI)
class UPFClientGetPlayFabIDsFromKongregateIDs : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientGetPlayFabIDsFromKongregateIDsResultDelegate OnSuccess;

    // Retrieves the unique PlayFab identifiers for the given set of Kongregate identifiers. The Kongregate identifiers are the IDs for the user accounts, available as "user_id" from the Kongregate API methods(ex: http://developers.kongregate.com/docs/client/getUserId).
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Account Management")
        static UPFClientGetPlayFabIDsFromKongregateIDs* GetPlayFabIDsFromKongregateIDs(class APlayerController* PlayerController, const FBPClientGetPlayFabIDsFromKongregateIDsRequest& InGetPlayFabIDsFromKongregateIDsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientGetPlayFabIDsFromKongregateIDsRequest Request;
    PlayFab::UPlayFabClientAPI::FGetPlayFabIDsFromKongregateIDsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FGetPlayFabIDsFromKongregateIDsResult& Result);
};
