// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientAddSharedGroupMembers.generated.h"

UCLASS(MinimalAPI)
class UPFClientAddSharedGroupMembers : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Adds users to the set of those able to update both the shared data, as well as the set of users  in the group. Only users in the group can add new members. Shared Groups are designed for sharing data between a very  small number of players, please see our guide: https://api.playfab.com/docs/tutorials/landing-players/shared-groups
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Shared Group Data")
        static UPFClientAddSharedGroupMembers* AddSharedGroupMembers(class APlayerController* PlayerController, const FBPClientAddSharedGroupMembersRequest& InAddSharedGroupMembersRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientAddSharedGroupMembersRequest Request;
    PlayFab::UPlayFabClientAPI::FAddSharedGroupMembersDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FAddSharedGroupMembersResult& Result);
};
