// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminGetTaskInstances.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminGetTaskInstances::UPFAdminGetTaskInstances(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FGetTaskInstancesDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminGetTaskInstances* UPFAdminGetTaskInstances::GetTaskInstances(class APlayerController* PlayerController, const FBPAdminGetTaskInstancesRequest& InGetTaskInstancesRequest)
{
    UPFAdminGetTaskInstances* Proxy = NewObject<UPFAdminGetTaskInstances>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetTaskInstancesRequest;
    
    return Proxy;
}

void UPFAdminGetTaskInstances::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if (AdminAPI.IsValid())
    {
        CallResult = AdminAPI->GetTaskInstances(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFAdminGetTaskInstances::OnSuccessCallback(const PlayFab::AdminModels::FGetTaskInstancesResult& Result)
{
    FBPAdminGetTaskInstancesResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
