// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminUpdateStoreItems.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminUpdateStoreItems::UPFAdminUpdateStoreItems(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FUpdateStoreItemsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminUpdateStoreItems* UPFAdminUpdateStoreItems::UpdateStoreItems(class APlayerController* PlayerController, const FBPAdminUpdateStoreItemsRequest& InUpdateStoreItemsRequest)
{
    UPFAdminUpdateStoreItems* Proxy = NewObject<UPFAdminUpdateStoreItems>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InUpdateStoreItemsRequest;
    
    return Proxy;
}

void UPFAdminUpdateStoreItems::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if (AdminAPI.IsValid())
    {
        CallResult = AdminAPI->UpdateStoreItems(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFAdminUpdateStoreItems::OnSuccessCallback(const PlayFab::AdminModels::FUpdateStoreItemsResult& Result)
{
    OnSuccess.Broadcast();
}
