// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminGetTasks.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminGetTasks::UPFAdminGetTasks(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FGetTasksDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminGetTasks* UPFAdminGetTasks::GetTasks(class APlayerController* PlayerController, const FBPAdminGetTasksRequest& InGetTasksRequest)
{
    UPFAdminGetTasks* Proxy = NewObject<UPFAdminGetTasks>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetTasksRequest;
    
    return Proxy;
}

void UPFAdminGetTasks::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if(AdminAPI.IsValid())
    {
        CallResult = AdminAPI->GetTasks(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFAdminGetTasks::OnSuccessCallback(const PlayFab::AdminModels::FGetTasksResult& Result)
{
    FBPAdminGetTasksResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
