// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminGetPlayerSharedSecrets.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminGetPlayerSharedSecrets::UPFAdminGetPlayerSharedSecrets(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FGetPlayerSharedSecretsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminGetPlayerSharedSecrets* UPFAdminGetPlayerSharedSecrets::GetPlayerSharedSecrets(class APlayerController* PlayerController)
{
    UPFAdminGetPlayerSharedSecrets* Proxy = NewObject<UPFAdminGetPlayerSharedSecrets>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    
    return Proxy;
}

void UPFAdminGetPlayerSharedSecrets::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if(AdminAPI.IsValid())
    {
        CallResult = AdminAPI->GetPlayerSharedSecrets(SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFAdminGetPlayerSharedSecrets::OnSuccessCallback(const PlayFab::AdminModels::FGetPlayerSharedSecretsResult& Result)
{
    FBPAdminGetPlayerSharedSecretsResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
