// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminDeleteTitle.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminDeleteTitle::UPFAdminDeleteTitle(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FDeleteTitleDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminDeleteTitle* UPFAdminDeleteTitle::DeleteTitle(class APlayerController* PlayerController)
{
    UPFAdminDeleteTitle* Proxy = NewObject<UPFAdminDeleteTitle>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    
    return Proxy;
}

void UPFAdminDeleteTitle::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if (AdminAPI.IsValid())
    {
        CallResult = AdminAPI->DeleteTitle(SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFAdminDeleteTitle::OnSuccessCallback(const PlayFab::AdminModels::FDeleteTitleResult& Result)
{
    OnSuccess.Broadcast();
}
