// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminGrantItemsToUsers.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminGrantItemsToUsers::UPFAdminGrantItemsToUsers(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FGrantItemsToUsersDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminGrantItemsToUsers* UPFAdminGrantItemsToUsers::GrantItemsToUsers(class APlayerController* PlayerController, const FBPAdminGrantItemsToUsersRequest& InGrantItemsToUsersRequest)
{
    UPFAdminGrantItemsToUsers* Proxy = NewObject<UPFAdminGrantItemsToUsers>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGrantItemsToUsersRequest;
    
    return Proxy;
}

void UPFAdminGrantItemsToUsers::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if(AdminAPI.IsValid())
    {
        CallResult = AdminAPI->GrantItemsToUsers(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFAdminGrantItemsToUsers::OnSuccessCallback(const PlayFab::AdminModels::FGrantItemsToUsersResult& Result)
{
    FBPAdminGrantItemsToUsersResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
