// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminGetUserData.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminGetUserData::UPFAdminGetUserData(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FGetUserDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminGetUserData* UPFAdminGetUserData::GetUserData(class APlayerController* PlayerController, const FBPAdminGetUserDataRequest& InGetUserDataRequest)
{
    UPFAdminGetUserData* Proxy = NewObject<UPFAdminGetUserData>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetUserDataRequest;
    
    return Proxy;
}

void UPFAdminGetUserData::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if (AdminAPI.IsValid())
    {
        CallResult = AdminAPI->GetUserData(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFAdminGetUserData::OnSuccessCallback(const PlayFab::AdminModels::FGetUserDataResult& Result)
{
    FBPAdminGetUserDataResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
