// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminGetPlayerSegments.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminGetPlayerSegments::UPFAdminGetPlayerSegments(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FGetPlayerSegmentsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminGetPlayerSegments* UPFAdminGetPlayerSegments::GetPlayerSegments(class APlayerController* PlayerController, const FBPAdminGetPlayersSegmentsRequest& InGetPlayersSegmentsRequest)
{
    UPFAdminGetPlayerSegments* Proxy = NewObject<UPFAdminGetPlayerSegments>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetPlayersSegmentsRequest;
    
    return Proxy;
}

void UPFAdminGetPlayerSegments::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if (AdminAPI.IsValid())
    {
        CallResult = AdminAPI->GetPlayerSegments(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFAdminGetPlayerSegments::OnSuccessCallback(const PlayFab::AdminModels::FGetPlayerSegmentsResult& Result)
{
    FBPAdminGetPlayerSegmentsResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
