// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientUpdateSharedGroupData.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientUpdateSharedGroupData::UPFClientUpdateSharedGroupData(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FUpdateSharedGroupDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientUpdateSharedGroupData* UPFClientUpdateSharedGroupData::UpdateSharedGroupData(class APlayerController* PlayerController, const FBPClientUpdateSharedGroupDataRequest& InUpdateSharedGroupDataRequest)
{
    UPFClientUpdateSharedGroupData* Proxy = NewObject<UPFClientUpdateSharedGroupData>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InUpdateSharedGroupDataRequest;
    
    return Proxy;
}

void UPFClientUpdateSharedGroupData::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->UpdateSharedGroupData(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientUpdateSharedGroupData::OnSuccessCallback(const PlayFab::ClientModels::FUpdateSharedGroupDataResult& Result)
{
    OnSuccess.Broadcast();
}
