// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientLoginWithGoogleAccount.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientLoginWithGoogleAccount::UPFClientLoginWithGoogleAccount(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FLoginWithGoogleAccountDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientLoginWithGoogleAccount* UPFClientLoginWithGoogleAccount::LoginWithGoogleAccount(class APlayerController* PlayerController, const FBPClientLoginWithGoogleAccountRequest& InLoginWithGoogleAccountRequest)
{
    UPFClientLoginWithGoogleAccount* Proxy = NewObject<UPFClientLoginWithGoogleAccount>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InLoginWithGoogleAccountRequest;
    
    return Proxy;
}

void UPFClientLoginWithGoogleAccount::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->LoginWithGoogleAccount(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientLoginWithGoogleAccount::OnSuccessCallback(const PlayFab::ClientModels::FLoginResult& Result)
{
    FBPClientLoginResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
