// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientLinkGameCenterAccount.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientLinkGameCenterAccount::UPFClientLinkGameCenterAccount(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FLinkGameCenterAccountDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientLinkGameCenterAccount* UPFClientLinkGameCenterAccount::LinkGameCenterAccount(class APlayerController* PlayerController, const FBPClientLinkGameCenterAccountRequest& InLinkGameCenterAccountRequest)
{
    UPFClientLinkGameCenterAccount* Proxy = NewObject<UPFClientLinkGameCenterAccount>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InLinkGameCenterAccountRequest;
    
    return Proxy;
}

void UPFClientLinkGameCenterAccount::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if (ClientAPI.IsValid())
    {
        CallResult = ClientAPI->LinkGameCenterAccount(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFClientLinkGameCenterAccount::OnSuccessCallback(const PlayFab::ClientModels::FLinkGameCenterAccountResult& Result)
{
    OnSuccess.Broadcast();
}
