// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientGetPlayerSegments.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientGetPlayerSegments::UPFClientGetPlayerSegments(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetPlayerSegmentsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientGetPlayerSegments* UPFClientGetPlayerSegments::GetPlayerSegments(class APlayerController* PlayerController)
{
    UPFClientGetPlayerSegments* Proxy = NewObject<UPFClientGetPlayerSegments>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    
    return Proxy;
}

void UPFClientGetPlayerSegments::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if (ClientAPI.IsValid())
    {
        CallResult = ClientAPI->GetPlayerSegments(SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFClientGetPlayerSegments::OnSuccessCallback(const PlayFab::ClientModels::FGetPlayerSegmentsResult& Result)
{
    FBPClientGetPlayerSegmentsResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
