// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientGetTitleData.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientGetTitleData::UPFClientGetTitleData(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetTitleDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientGetTitleData* UPFClientGetTitleData::GetTitleData(class APlayerController* PlayerController, const FBPClientGetTitleDataRequest& InGetTitleDataRequest)
{
    UPFClientGetTitleData* Proxy = NewObject<UPFClientGetTitleData>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetTitleDataRequest;
    
    return Proxy;
}

void UPFClientGetTitleData::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->GetTitleData(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientGetTitleData::OnSuccessCallback(const PlayFab::ClientModels::FGetTitleDataResult& Result)
{
    FBPClientGetTitleDataResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
