// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientGetAccountInfo.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientGetAccountInfo::UPFClientGetAccountInfo(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetAccountInfoDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientGetAccountInfo* UPFClientGetAccountInfo::GetAccountInfo(class APlayerController* PlayerController, const FBPClientGetAccountInfoRequest& InGetAccountInfoRequest)
{
    UPFClientGetAccountInfo* Proxy = NewObject<UPFClientGetAccountInfo>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetAccountInfoRequest;
    
    return Proxy;
}

void UPFClientGetAccountInfo::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->GetAccountInfo(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientGetAccountInfo::OnSuccessCallback(const PlayFab::ClientModels::FGetAccountInfoResult& Result)
{
    FBPClientGetAccountInfoResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
