// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientSetFriendTags.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientSetFriendTags::UPFClientSetFriendTags(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FSetFriendTagsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientSetFriendTags* UPFClientSetFriendTags::SetFriendTags(class APlayerController* PlayerController, const FBPClientSetFriendTagsRequest& InSetFriendTagsRequest)
{
    UPFClientSetFriendTags* Proxy = NewObject<UPFClientSetFriendTags>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InSetFriendTagsRequest;
    
    return Proxy;
}

void UPFClientSetFriendTags::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if (ClientAPI.IsValid())
    {
        CallResult = ClientAPI->SetFriendTags(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFClientSetFriendTags::OnSuccessCallback(const PlayFab::ClientModels::FSetFriendTagsResult& Result)
{
    OnSuccess.Broadcast();
}
