// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientGetContentDownloadUrl.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientGetContentDownloadUrl::UPFClientGetContentDownloadUrl(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetContentDownloadUrlDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientGetContentDownloadUrl* UPFClientGetContentDownloadUrl::GetContentDownloadUrl(class APlayerController* PlayerController, const FBPClientGetContentDownloadUrlRequest& InGetContentDownloadUrlRequest)
{
    UPFClientGetContentDownloadUrl* Proxy = NewObject<UPFClientGetContentDownloadUrl>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetContentDownloadUrlRequest;
    
    return Proxy;
}

void UPFClientGetContentDownloadUrl::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->GetContentDownloadUrl(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientGetContentDownloadUrl::OnSuccessCallback(const PlayFab::ClientModels::FGetContentDownloadUrlResult& Result)
{
    FBPClientGetContentDownloadUrlResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
