// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientGetPhotonAuthenticationToken.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientGetPhotonAuthenticationToken::UPFClientGetPhotonAuthenticationToken(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetPhotonAuthenticationTokenDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientGetPhotonAuthenticationToken* UPFClientGetPhotonAuthenticationToken::GetPhotonAuthenticationToken(class APlayerController* PlayerController, const FBPClientGetPhotonAuthenticationTokenRequest& InGetPhotonAuthenticationTokenRequest)
{
    UPFClientGetPhotonAuthenticationToken* Proxy = NewObject<UPFClientGetPhotonAuthenticationToken>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetPhotonAuthenticationTokenRequest;
    
    return Proxy;
}

void UPFClientGetPhotonAuthenticationToken::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if (ClientAPI.IsValid())
    {
        CallResult = ClientAPI->GetPhotonAuthenticationToken(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFClientGetPhotonAuthenticationToken::OnSuccessCallback(const PlayFab::ClientModels::FGetPhotonAuthenticationTokenResult& Result)
{
    FBPClientGetPhotonAuthenticationTokenResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
