// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientAddUserVirtualCurrency.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientAddUserVirtualCurrency::UPFClientAddUserVirtualCurrency(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FAddUserVirtualCurrencyDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientAddUserVirtualCurrency* UPFClientAddUserVirtualCurrency::AddUserVirtualCurrency(class APlayerController* PlayerController, const FBPClientAddUserVirtualCurrencyRequest& InAddUserVirtualCurrencyRequest)
{
    UPFClientAddUserVirtualCurrency* Proxy = NewObject<UPFClientAddUserVirtualCurrency>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InAddUserVirtualCurrencyRequest;
    
    return Proxy;
}

void UPFClientAddUserVirtualCurrency::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if (ClientAPI.IsValid())
    {
        CallResult = ClientAPI->AddUserVirtualCurrency(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFClientAddUserVirtualCurrency::OnSuccessCallback(const PlayFab::ClientModels::FModifyUserVirtualCurrencyResult& Result)
{
    FBPClientModifyUserVirtualCurrencyResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
