// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientLinkCustomID.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientLinkCustomID::UPFClientLinkCustomID(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FLinkCustomIDDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientLinkCustomID* UPFClientLinkCustomID::LinkCustomID(class APlayerController* PlayerController, const FBPClientLinkCustomIDRequest& InLinkCustomIDRequest)
{
    UPFClientLinkCustomID* Proxy = NewObject<UPFClientLinkCustomID>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InLinkCustomIDRequest;
    
    return Proxy;
}

void UPFClientLinkCustomID::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if (ClientAPI.IsValid())
    {
        CallResult = ClientAPI->LinkCustomID(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFClientLinkCustomID::OnSuccessCallback(const PlayFab::ClientModels::FLinkCustomIDResult& Result)
{
    OnSuccess.Broadcast();
}
