// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientRegisterForIOSPushNotification.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientRegisterForIOSPushNotification::UPFClientRegisterForIOSPushNotification(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FRegisterForIOSPushNotificationDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientRegisterForIOSPushNotification* UPFClientRegisterForIOSPushNotification::RegisterForIOSPushNotification(class APlayerController* PlayerController, const FBPClientRegisterForIOSPushNotificationRequest& InRegisterForIOSPushNotificationRequest)
{
    UPFClientRegisterForIOSPushNotification* Proxy = NewObject<UPFClientRegisterForIOSPushNotification>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InRegisterForIOSPushNotificationRequest;
    
    return Proxy;
}

void UPFClientRegisterForIOSPushNotification::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->RegisterForIOSPushNotification(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientRegisterForIOSPushNotification::OnSuccessCallback(const PlayFab::ClientModels::FRegisterForIOSPushNotificationResult& Result)
{
    OnSuccess.Broadcast();
}
