// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientAddSharedGroupMembers.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientAddSharedGroupMembers::UPFClientAddSharedGroupMembers(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FAddSharedGroupMembersDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientAddSharedGroupMembers* UPFClientAddSharedGroupMembers::AddSharedGroupMembers(class APlayerController* PlayerController, const FBPClientAddSharedGroupMembersRequest& InAddSharedGroupMembersRequest)
{
    UPFClientAddSharedGroupMembers* Proxy = NewObject<UPFClientAddSharedGroupMembers>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InAddSharedGroupMembersRequest;
    
    return Proxy;
}

void UPFClientAddSharedGroupMembers::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->AddSharedGroupMembers(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientAddSharedGroupMembers::OnSuccessCallback(const PlayFab::ClientModels::FAddSharedGroupMembersResult& Result)
{
    OnSuccess.Broadcast();
}
