// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientValidateGooglePlayPurchase.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientValidateGooglePlayPurchase::UPFClientValidateGooglePlayPurchase(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FValidateGooglePlayPurchaseDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientValidateGooglePlayPurchase* UPFClientValidateGooglePlayPurchase::ValidateGooglePlayPurchase(class APlayerController* PlayerController, const FBPClientValidateGooglePlayPurchaseRequest& InValidateGooglePlayPurchaseRequest)
{
    UPFClientValidateGooglePlayPurchase* Proxy = NewObject<UPFClientValidateGooglePlayPurchase>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InValidateGooglePlayPurchaseRequest;
    
    return Proxy;
}

void UPFClientValidateGooglePlayPurchase::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if (ClientAPI.IsValid())
    {
        CallResult = ClientAPI->ValidateGooglePlayPurchase(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFClientValidateGooglePlayPurchase::OnSuccessCallback(const PlayFab::ClientModels::FValidateGooglePlayPurchaseResult& Result)
{
    OnSuccess.Broadcast();
}
