// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientUnlinkTwitch.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientUnlinkTwitch::UPFClientUnlinkTwitch(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FUnlinkTwitchDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientUnlinkTwitch* UPFClientUnlinkTwitch::UnlinkTwitch(class APlayerController* PlayerController)
{
    UPFClientUnlinkTwitch* Proxy = NewObject<UPFClientUnlinkTwitch>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    
    return Proxy;
}

void UPFClientUnlinkTwitch::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if (ClientAPI.IsValid())
    {
        CallResult = ClientAPI->UnlinkTwitch(SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFClientUnlinkTwitch::OnSuccessCallback(const PlayFab::ClientModels::FUnlinkTwitchAccountResult& Result)
{
    OnSuccess.Broadcast();
}
