// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientUnlinkWindowsHello.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientUnlinkWindowsHello::UPFClientUnlinkWindowsHello(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FUnlinkWindowsHelloDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientUnlinkWindowsHello* UPFClientUnlinkWindowsHello::UnlinkWindowsHello(class APlayerController* PlayerController, const FBPClientUnlinkWindowsHelloAccountRequest& InUnlinkWindowsHelloAccountRequest)
{
    UPFClientUnlinkWindowsHello* Proxy = NewObject<UPFClientUnlinkWindowsHello>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InUnlinkWindowsHelloAccountRequest;
    
    return Proxy;
}

void UPFClientUnlinkWindowsHello::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->UnlinkWindowsHello(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientUnlinkWindowsHello::OnSuccessCallback(const PlayFab::ClientModels::FUnlinkWindowsHelloAccountResponse& Result)
{
    OnSuccess.Broadcast();
}
