// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientExecuteCloudScript.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientExecuteCloudScript::UPFClientExecuteCloudScript(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FExecuteCloudScriptDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientExecuteCloudScript* UPFClientExecuteCloudScript::ExecuteCloudScript(class APlayerController* PlayerController, const FBPClientExecuteCloudScriptRequest& InExecuteCloudScriptRequest)
{
    UPFClientExecuteCloudScript* Proxy = NewObject<UPFClientExecuteCloudScript>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InExecuteCloudScriptRequest;
    
    return Proxy;
}

void UPFClientExecuteCloudScript::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if (ClientAPI.IsValid())
    {
        CallResult = ClientAPI->ExecuteCloudScript(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFClientExecuteCloudScript::OnSuccessCallback(const PlayFab::ClientModels::FExecuteCloudScriptResult& Result)
{
    FBPClientExecuteCloudScriptResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
