// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientWriteCharacterEvent.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientWriteCharacterEvent::UPFClientWriteCharacterEvent(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FWriteCharacterEventDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientWriteCharacterEvent* UPFClientWriteCharacterEvent::WriteCharacterEvent(class APlayerController* PlayerController, const FBPClientWriteClientCharacterEventRequest& InWriteClientCharacterEventRequest)
{
    UPFClientWriteCharacterEvent* Proxy = NewObject<UPFClientWriteCharacterEvent>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InWriteClientCharacterEventRequest;
    
    return Proxy;
}

void UPFClientWriteCharacterEvent::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->WriteCharacterEvent(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientWriteCharacterEvent::OnSuccessCallback(const PlayFab::ClientModels::FWriteEventResponse& Result)
{
    FBPClientWriteEventResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
