// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientLoginWithIOSDeviceID.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientLoginWithIOSDeviceID::UPFClientLoginWithIOSDeviceID(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FLoginWithIOSDeviceIDDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientLoginWithIOSDeviceID* UPFClientLoginWithIOSDeviceID::LoginWithIOSDeviceID(class APlayerController* PlayerController, const FBPClientLoginWithIOSDeviceIDRequest& InLoginWithIOSDeviceIDRequest)
{
    UPFClientLoginWithIOSDeviceID* Proxy = NewObject<UPFClientLoginWithIOSDeviceID>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InLoginWithIOSDeviceIDRequest;
    
    return Proxy;
}

void UPFClientLoginWithIOSDeviceID::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if (ClientAPI.IsValid())
    {
        CallResult = ClientAPI->LoginWithIOSDeviceID(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFClientLoginWithIOSDeviceID::OnSuccessCallback(const PlayFab::ClientModels::FLoginResult& Result)
{
    FBPClientLoginResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
