// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientGetTitlePublicKey.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientGetTitlePublicKey::UPFClientGetTitlePublicKey(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetTitlePublicKeyDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientGetTitlePublicKey* UPFClientGetTitlePublicKey::GetTitlePublicKey(class APlayerController* PlayerController, const FBPClientGetTitlePublicKeyRequest& InGetTitlePublicKeyRequest)
{
    UPFClientGetTitlePublicKey* Proxy = NewObject<UPFClientGetTitlePublicKey>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetTitlePublicKeyRequest;
    
    return Proxy;
}

void UPFClientGetTitlePublicKey::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if (ClientAPI.IsValid())
    {
        CallResult = ClientAPI->GetTitlePublicKey(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFClientGetTitlePublicKey::OnSuccessCallback(const PlayFab::ClientModels::FGetTitlePublicKeyResult& Result)
{
    FBPClientGetTitlePublicKeyResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
