// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientLinkAndroidDeviceID.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientLinkAndroidDeviceID::UPFClientLinkAndroidDeviceID(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FLinkAndroidDeviceIDDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientLinkAndroidDeviceID* UPFClientLinkAndroidDeviceID::LinkAndroidDeviceID(class APlayerController* PlayerController, const FBPClientLinkAndroidDeviceIDRequest& InLinkAndroidDeviceIDRequest)
{
    UPFClientLinkAndroidDeviceID* Proxy = NewObject<UPFClientLinkAndroidDeviceID>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InLinkAndroidDeviceIDRequest;
    
    return Proxy;
}

void UPFClientLinkAndroidDeviceID::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if (ClientAPI.IsValid())
    {
        CallResult = ClientAPI->LinkAndroidDeviceID(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFClientLinkAndroidDeviceID::OnSuccessCallback(const PlayFab::ClientModels::FLinkAndroidDeviceIDResult& Result)
{
    OnSuccess.Broadcast();
}
