// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFClientGetPublisherData.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFClientGetPublisherData::UPFClientGetPublisherData(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabClientAPI::FGetPublisherDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFClientGetPublisherData* UPFClientGetPublisherData::GetPublisherData(class APlayerController* PlayerController, const FBPClientGetPublisherDataRequest& InGetPublisherDataRequest)
{
    UPFClientGetPublisherData* Proxy = NewObject<UPFClientGetPublisherData>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetPublisherDataRequest;
    
    return Proxy;
}

void UPFClientGetPublisherData::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabClientPtr ClientAPI = IPlayFabModuleInterface::Get().GetClientAPI();

    bool CallResult = false;

    if(ClientAPI.IsValid())
    {
        CallResult = ClientAPI->GetPublisherData(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFClientGetPublisherData::OnSuccessCallback(const PlayFab::ClientModels::FGetPublisherDataResult& Result)
{
    FBPClientGetPublisherDataResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
