// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFServerGetPlayerProfile.h"

UPFServerGetPlayerProfile::UPFServerGetPlayerProfile(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabServerAPI::FGetPlayerProfileDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFServerGetPlayerProfile* UPFServerGetPlayerProfile::GetPlayerProfile(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InPlayFabId, const FBPServerPlayerProfileViewConstraints& InProfileConstraints)
{
	UPFServerGetPlayerProfile* Proxy = NewObject<UPFServerGetPlayerProfile>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.PlayFabId = InPlayFabId;
	*Proxy->Request.ProfileConstraints = InProfileConstraints.Data;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFServerGetPlayerProfile::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

	bool CallResult = false;

	if(ServerAPI.IsValid())
	{	
		CallResult = ServerAPI->GetPlayerProfile(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPServerGetPlayerProfileResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFServerGetPlayerProfile::OnSuccessCallback(const PlayFab::ServerModels::FGetPlayerProfileResult& Result)
{
	FBPServerGetPlayerProfileResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFServerGetPlayerProfile::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPServerGetPlayerProfileResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
