// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerSetGameServerInstanceData.generated.h"

UCLASS(MinimalAPI)
class UPFServerSetGameServerInstanceData : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Sets the custom data of the indicated Game Server Instance
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Matchmaking")
        static UPFServerSetGameServerInstanceData* SetGameServerInstanceData(class APlayerController* PlayerController, const FBPServerSetGameServerInstanceDataRequest& InSetGameServerInstanceDataRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerSetGameServerInstanceDataRequest Request;
    PlayFab::UPlayFabServerAPI::FSetGameServerInstanceDataDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FSetGameServerInstanceDataResult& Result);
};
