// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerAddFriend.generated.h"

UCLASS(MinimalAPI)
class UPFServerAddFriend : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Adds the Friend user to the friendlist of the user with PlayFabId. At least one of FriendPlayFabId,FriendUsername,FriendEmail, or FriendTitleDisplayName should be initialized.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Friend List Management")
        static UPFServerAddFriend* AddFriend(class APlayerController* PlayerController, const FBPServerAddFriendRequest& InAddFriendRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerAddFriendRequest Request;
    PlayFab::UPlayFabServerAPI::FAddFriendDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FEmptyResult& Result);
};
