// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerSubtractCharacterVirtualCurrency.generated.h"

UCLASS(MinimalAPI)
class UPFServerSubtractCharacterVirtualCurrency : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerModifyCharacterVirtualCurrencyResultDelegate OnSuccess;

    // Decrements the character's balance of the specified virtual currency by the stated amount. It is possible to make a VC balance negative with this API.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Player Item Management")
        static UPFServerSubtractCharacterVirtualCurrency* SubtractCharacterVirtualCurrency(class APlayerController* PlayerController, const FBPServerSubtractCharacterVirtualCurrencyRequest& InSubtractCharacterVirtualCurrencyRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerSubtractCharacterVirtualCurrencyRequest Request;
    PlayFab::UPlayFabServerAPI::FSubtractCharacterVirtualCurrencyDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FModifyCharacterVirtualCurrencyResult& Result);
};
