// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetUserBans.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetUserBans : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGetUserBansResultDelegate OnSuccess;

    // Gets all bans for a user.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Account Management")
        static UPFServerGetUserBans* GetUserBans(class APlayerController* PlayerController, const FBPServerGetUserBansRequest& InGetUserBansRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGetUserBansRequest Request;
    PlayFab::UPlayFabServerAPI::FGetUserBansDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGetUserBansResult& Result);
};
