// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetFriendLeaderboard.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetFriendLeaderboard : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGetLeaderboardResultDelegate OnSuccess;

    // Retrieves a list of ranked friends of the given player for the given statistic, starting from the indicated point in the leaderboard
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Player Data Management")
        static UPFServerGetFriendLeaderboard* GetFriendLeaderboard(class APlayerController* PlayerController, const FBPServerGetFriendLeaderboardRequest& InGetFriendLeaderboardRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGetFriendLeaderboardRequest Request;
    PlayFab::UPlayFabServerAPI::FGetFriendLeaderboardDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGetLeaderboardResult& Result);
};
