// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGrantItemsToUsers.generated.h"

UCLASS(MinimalAPI)
class UPFServerGrantItemsToUsers : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGrantItemsToUsersResultDelegate OnSuccess;

    // Adds the specified items to the specified user inventories
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Player Item Management")
        static UPFServerGrantItemsToUsers* GrantItemsToUsers(class APlayerController* PlayerController, const FBPServerGrantItemsToUsersRequest& InGrantItemsToUsersRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGrantItemsToUsersRequest Request;
    PlayFab::UPlayFabServerAPI::FGrantItemsToUsersDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGrantItemsToUsersResult& Result);
};
