// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerSubtractUserVirtualCurrency.generated.h"

UCLASS(MinimalAPI)
class UPFServerSubtractUserVirtualCurrency : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerModifyUserVirtualCurrencyResultDelegate OnSuccess;

    // Decrements the user's balance of the specified virtual currency by the stated amount. It is possible to make a VC balance negative with this API.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Player Item Management")
        static UPFServerSubtractUserVirtualCurrency* SubtractUserVirtualCurrency(class APlayerController* PlayerController, const FBPServerSubtractUserVirtualCurrencyRequest& InSubtractUserVirtualCurrencyRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerSubtractUserVirtualCurrencyRequest Request;
    PlayFab::UPlayFabServerAPI::FSubtractUserVirtualCurrencyDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FModifyUserVirtualCurrencyResult& Result);
};
