// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetCharacterLeaderboard.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetCharacterLeaderboard : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGetCharacterLeaderboardResultDelegate OnSuccess;

    // Retrieves a list of ranked characters for the given statistic, starting from the indicated point in the leaderboard
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Characters")
        static UPFServerGetCharacterLeaderboard* GetCharacterLeaderboard(class APlayerController* PlayerController, const FBPServerGetCharacterLeaderboardRequest& InGetCharacterLeaderboardRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGetCharacterLeaderboardRequest Request;
    PlayFab::UPlayFabServerAPI::FGetCharacterLeaderboardDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGetCharacterLeaderboardResult& Result);
};
