// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetPlayerTags.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetPlayerTags : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGetPlayerTagsResultDelegate OnSuccess;

    // Get all tags with a given Namespace (optional) from a player profile.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|PlayStream")
        static UPFServerGetPlayerTags* GetPlayerTags(class APlayerController* PlayerController, const FBPServerGetPlayerTagsRequest& InGetPlayerTagsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGetPlayerTagsRequest Request;
    PlayFab::UPlayFabServerAPI::FGetPlayerTagsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGetPlayerTagsResult& Result);
};
