// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetCatalogItems.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetCatalogItems : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGetCatalogItemsResultDelegate OnSuccess;

    // Retrieves the specified version of the title's catalog of virtual goods, including all defined properties
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Title-Wide Data Management")
        static UPFServerGetCatalogItems* GetCatalogItems(class APlayerController* PlayerController, const FBPServerGetCatalogItemsRequest& InGetCatalogItemsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGetCatalogItemsRequest Request;
    PlayFab::UPlayFabServerAPI::FGetCatalogItemsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGetCatalogItemsResult& Result);
};
