// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerDeleteUsers.generated.h"

UCLASS(MinimalAPI)
class UPFServerDeleteUsers : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Deletes the users for the provided game. Deletes custom data, all account linkages, and statistics.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Player Data Management")
        static UPFServerDeleteUsers* DeleteUsers(class APlayerController* PlayerController, const FBPServerDeleteUsersRequest& InDeleteUsersRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerDeleteUsersRequest Request;
    PlayFab::UPlayFabServerAPI::FDeleteUsersDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FDeleteUsersResult& Result);
};
