// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetCharacterReadOnlyData.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetCharacterReadOnlyData : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGetCharacterDataResultDelegate OnSuccess;

    // Retrieves the title-specific custom data for the user's character which can only be read by the client
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Character Data")
        static UPFServerGetCharacterReadOnlyData* GetCharacterReadOnlyData(class APlayerController* PlayerController, const FBPServerGetCharacterDataRequest& InGetCharacterDataRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGetCharacterDataRequest Request;
    PlayFab::UPlayFabServerAPI::FGetCharacterReadOnlyDataDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGetCharacterDataResult& Result);
};
