// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerMoveItemToCharacterFromCharacter.generated.h"

UCLASS(MinimalAPI)
class UPFServerMoveItemToCharacterFromCharacter : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Moves an item from a character's inventory into another of the users's character's inventory.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Player Item Management")
        static UPFServerMoveItemToCharacterFromCharacter* MoveItemToCharacterFromCharacter(class APlayerController* PlayerController, const FBPServerMoveItemToCharacterFromCharacterRequest& InMoveItemToCharacterFromCharacterRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerMoveItemToCharacterFromCharacterRequest Request;
    PlayFab::UPlayFabServerAPI::FMoveItemToCharacterFromCharacterDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FMoveItemToCharacterFromCharacterResult& Result);
};
