// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetPlayerStatisticVersions.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetPlayerStatisticVersions : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGetPlayerStatisticVersionsResultDelegate OnSuccess;

    // Retrieves the information on the available versions of the specified statistic.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Player Data Management")
        static UPFServerGetPlayerStatisticVersions* GetPlayerStatisticVersions(class APlayerController* PlayerController, const FBPServerGetPlayerStatisticVersionsRequest& InGetPlayerStatisticVersionsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGetPlayerStatisticVersionsRequest Request;
    PlayFab::UPlayFabServerAPI::FGetPlayerStatisticVersionsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGetPlayerStatisticVersionsResult& Result);
};
