// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetLeaderboardAroundCharacter.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetLeaderboardAroundCharacter : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGetLeaderboardAroundCharacterResultDelegate OnSuccess;

    // Retrieves a list of ranked characters for the given statistic, centered on the requested user
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Characters")
        static UPFServerGetLeaderboardAroundCharacter* GetLeaderboardAroundCharacter(class APlayerController* PlayerController, const FBPServerGetLeaderboardAroundCharacterRequest& InGetLeaderboardAroundCharacterRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGetLeaderboardAroundCharacterRequest Request;
    PlayFab::UPlayFabServerAPI::FGetLeaderboardAroundCharacterDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGetLeaderboardAroundCharacterResult& Result);
};
