// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerRegisterGame.generated.h"

UCLASS(MinimalAPI)
class UPFServerRegisterGame : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerRegisterGameResponseDelegate OnSuccess;

    // Inform the matchmaker that a new Game Server Instance is added.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Matchmaking")
        static UPFServerRegisterGame* RegisterGame(class APlayerController* PlayerController, const FBPServerRegisterGameRequest& InRegisterGameRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerRegisterGameRequest Request;
    PlayFab::UPlayFabServerAPI::FRegisterGameDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FRegisterGameResponse& Result);
};
