// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetPlayFabIDsFromSteamIDs.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetPlayFabIDsFromSteamIDs : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGetPlayFabIDsFromSteamIDsResultDelegate OnSuccess;

    // Retrieves the unique PlayFab identifiers for the given set of Steam identifiers. The Steam identifiers  are the profile IDs for the user accounts, available as SteamId in the Steamworks Community API calls.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Account Management")
        static UPFServerGetPlayFabIDsFromSteamIDs* GetPlayFabIDsFromSteamIDs(class APlayerController* PlayerController, const FBPServerGetPlayFabIDsFromSteamIDsRequest& InGetPlayFabIDsFromSteamIDsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGetPlayFabIDsFromSteamIDsRequest Request;
    PlayFab::UPlayFabServerAPI::FGetPlayFabIDsFromSteamIDsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGetPlayFabIDsFromSteamIDsResult& Result);
};
