// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetPlayerProfile.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetPlayerProfile : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGetPlayerProfileResultDelegate OnSuccess;

    // Retrieves the player's profile
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Account Management")
        static UPFServerGetPlayerProfile* GetPlayerProfile(class APlayerController* PlayerController, const FBPServerGetPlayerProfileRequest& InGetPlayerProfileRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGetPlayerProfileRequest Request;
    PlayFab::UPlayFabServerAPI::FGetPlayerProfileDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGetPlayerProfileResult& Result);
};
