// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerMoveItemToCharacterFromUser.generated.h"

UCLASS(MinimalAPI)
class UPFServerMoveItemToCharacterFromUser : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Moves an item from a user's inventory into their character's inventory.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Player Item Management")
        static UPFServerMoveItemToCharacterFromUser* MoveItemToCharacterFromUser(class APlayerController* PlayerController, const FBPServerMoveItemToCharacterFromUserRequest& InMoveItemToCharacterFromUserRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerMoveItemToCharacterFromUserRequest Request;
    PlayFab::UPlayFabServerAPI::FMoveItemToCharacterFromUserDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FMoveItemToCharacterFromUserResult& Result);
};
