// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetUserData.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetUserData : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGetUserDataResultDelegate OnSuccess;

    // Retrieves the title-specific custom data for the user which is readable and writable by the client
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Player Data Management")
        static UPFServerGetUserData* GetUserData(class APlayerController* PlayerController, const FBPServerGetUserDataRequest& InGetUserDataRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGetUserDataRequest Request;
    PlayFab::UPlayFabServerAPI::FGetUserDataDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGetUserDataResult& Result);
};
