// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGrantItemsToCharacter.generated.h"

UCLASS(MinimalAPI)
class UPFServerGrantItemsToCharacter : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGrantItemsToCharacterResultDelegate OnSuccess;

    // Adds the specified items to the specified character's inventory
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Player Item Management")
        static UPFServerGrantItemsToCharacter* GrantItemsToCharacter(class APlayerController* PlayerController, const FBPServerGrantItemsToCharacterRequest& InGrantItemsToCharacterRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGrantItemsToCharacterRequest Request;
    PlayFab::UPlayFabServerAPI::FGrantItemsToCharacterDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGrantItemsToCharacterResult& Result);
};
