// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetPlayerSegments.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetPlayerSegments : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGetPlayerSegmentsResultDelegate OnSuccess;

    // List all segments that a player currently belongs to at this moment in time.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|PlayStream")
        static UPFServerGetPlayerSegments* GetPlayerSegments(class APlayerController* PlayerController, const FBPServerGetPlayersSegmentsRequest& InGetPlayersSegmentsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGetPlayersSegmentsRequest Request;
    PlayFab::UPlayFabServerAPI::FGetPlayerSegmentsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGetPlayerSegmentsResult& Result);
};
