// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerWriteTitleEvent.generated.h"

UCLASS(MinimalAPI)
class UPFServerWriteTitleEvent : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerWriteEventResponseDelegate OnSuccess;

    // Writes a title-based event into PlayStream.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Analytics")
        static UPFServerWriteTitleEvent* WriteTitleEvent(class APlayerController* PlayerController, const FBPServerWriteTitleEventRequest& InWriteTitleEventRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerWriteTitleEventRequest Request;
    PlayFab::UPlayFabServerAPI::FWriteTitleEventDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FWriteEventResponse& Result);
};
