// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerSetPublisherData.generated.h"

UCLASS(MinimalAPI)
class UPFServerSetPublisherData : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Updates the key-value store of custom publisher settings
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Title-Wide Data Management")
        static UPFServerSetPublisherData* SetPublisherData(class APlayerController* PlayerController, const FBPServerSetPublisherDataRequest& InSetPublisherDataRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerSetPublisherDataRequest Request;
    PlayFab::UPlayFabServerAPI::FSetPublisherDataDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FSetPublisherDataResult& Result);
};
