// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetPublisherData.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetPublisherData : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGetPublisherDataResultDelegate OnSuccess;

    // Retrieves the key-value store of custom publisher settings
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Title-Wide Data Management")
        static UPFServerGetPublisherData* GetPublisherData(class APlayerController* PlayerController, const FBPServerGetPublisherDataRequest& InGetPublisherDataRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGetPublisherDataRequest Request;
    PlayFab::UPlayFabServerAPI::FGetPublisherDataDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGetPublisherDataResult& Result);
};
