// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetAllUsersCharacters.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetAllUsersCharacters : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerListUsersCharactersResultDelegate OnSuccess;

    // Lists all of the characters that belong to a specific user. CharacterIds are not globally unique; characterId must be evaluated with the parent PlayFabId to guarantee uniqueness.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Characters")
        static UPFServerGetAllUsersCharacters* GetAllUsersCharacters(class APlayerController* PlayerController, const FBPServerListUsersCharactersRequest& InListUsersCharactersRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerListUsersCharactersRequest Request;
    PlayFab::UPlayFabServerAPI::FGetAllUsersCharactersDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FListUsersCharactersResult& Result);
};
