// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetFriendsList.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetFriendsList : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGetFriendsListResultDelegate OnSuccess;

    // Retrieves the current friends for the user with PlayFabId, constrained to users who have PlayFab accounts. Friends from linked accounts (Facebook, Steam) are also included. You may optionally exclude some linked services' friends.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Friend List Management")
        static UPFServerGetFriendsList* GetFriendsList(class APlayerController* PlayerController, const FBPServerGetFriendsListRequest& InGetFriendsListRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGetFriendsListRequest Request;
    PlayFab::UPlayFabServerAPI::FGetFriendsListDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGetFriendsListResult& Result);
};
