// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerExecuteCloudScript.generated.h"

UCLASS(MinimalAPI)
class UPFServerExecuteCloudScript : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerExecuteCloudScriptResultDelegate OnSuccess;

    // Executes a CloudScript function, with the 'currentPlayerId' variable set to the specified PlayFabId parameter value.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Server-Side Cloud Script")
        static UPFServerExecuteCloudScript* ExecuteCloudScript(class APlayerController* PlayerController, const FBPServerExecuteCloudScriptServerRequest& InExecuteCloudScriptServerRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerExecuteCloudScriptServerRequest Request;
    PlayFab::UPlayFabServerAPI::FExecuteCloudScriptDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FExecuteCloudScriptResult& Result);
};
