// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerUpdatePlayerStatistics.generated.h"

UCLASS(MinimalAPI)
class UPFServerUpdatePlayerStatistics : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Updates the values of the specified title-specific statistics for the user
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Player Data Management")
        static UPFServerUpdatePlayerStatistics* UpdatePlayerStatistics(class APlayerController* PlayerController, const FBPServerUpdatePlayerStatisticsRequest& InUpdatePlayerStatisticsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerUpdatePlayerStatisticsRequest Request;
    PlayFab::UPlayFabServerAPI::FUpdatePlayerStatisticsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FUpdatePlayerStatisticsResult& Result);
};
