// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerRevokeBans.generated.h"

UCLASS(MinimalAPI)
class UPFServerRevokeBans : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerRevokeBansResultDelegate OnSuccess;

    // Revoke all active bans specified with BanId.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Account Management")
        static UPFServerRevokeBans* RevokeBans(class APlayerController* PlayerController, const FBPServerRevokeBansRequest& InRevokeBansRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerRevokeBansRequest Request;
    PlayFab::UPlayFabServerAPI::FRevokeBansDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FRevokeBansResult& Result);
};
