// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerGetUserInventory.generated.h"

UCLASS(MinimalAPI)
class UPFServerGetUserInventory : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerGetUserInventoryResultDelegate OnSuccess;

    // Retrieves the specified user's current inventory of virtual goods
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Player Item Management")
        static UPFServerGetUserInventory* GetUserInventory(class APlayerController* PlayerController, const FBPServerGetUserInventoryRequest& InGetUserInventoryRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerGetUserInventoryRequest Request;
    PlayFab::UPlayFabServerAPI::FGetUserInventoryDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FGetUserInventoryResult& Result);
};
