// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerUpdateCharacterData.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerUpdateCharacterData::UPFServerUpdateCharacterData(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FUpdateCharacterDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerUpdateCharacterData* UPFServerUpdateCharacterData::UpdateCharacterData(class APlayerController* PlayerController, const FBPServerUpdateCharacterDataRequest& InUpdateCharacterDataRequest)
{
    UPFServerUpdateCharacterData* Proxy = NewObject<UPFServerUpdateCharacterData>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InUpdateCharacterDataRequest;
    
    return Proxy;
}

void UPFServerUpdateCharacterData::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if(ServerAPI.IsValid())
    {
        CallResult = ServerAPI->UpdateCharacterData(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFServerUpdateCharacterData::OnSuccessCallback(const PlayFab::ServerModels::FUpdateCharacterDataResult& Result)
{
    FBPServerUpdateCharacterDataResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
