// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerUpdateUserPublisherInternalData.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerUpdateUserPublisherInternalData::UPFServerUpdateUserPublisherInternalData(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FUpdateUserPublisherInternalDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerUpdateUserPublisherInternalData* UPFServerUpdateUserPublisherInternalData::UpdateUserPublisherInternalData(class APlayerController* PlayerController, const FBPServerUpdateUserInternalDataRequest& InUpdateUserInternalDataRequest)
{
    UPFServerUpdateUserPublisherInternalData* Proxy = NewObject<UPFServerUpdateUserPublisherInternalData>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InUpdateUserInternalDataRequest;
    
    return Proxy;
}

void UPFServerUpdateUserPublisherInternalData::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if(ServerAPI.IsValid())
    {
        CallResult = ServerAPI->UpdateUserPublisherInternalData(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFServerUpdateUserPublisherInternalData::OnSuccessCallback(const PlayFab::ServerModels::FUpdateUserDataResult& Result)
{
    FBPServerUpdateUserDataResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
