// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerAddUserVirtualCurrency.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerAddUserVirtualCurrency::UPFServerAddUserVirtualCurrency(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FAddUserVirtualCurrencyDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerAddUserVirtualCurrency* UPFServerAddUserVirtualCurrency::AddUserVirtualCurrency(class APlayerController* PlayerController, const FBPServerAddUserVirtualCurrencyRequest& InAddUserVirtualCurrencyRequest)
{
    UPFServerAddUserVirtualCurrency* Proxy = NewObject<UPFServerAddUserVirtualCurrency>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InAddUserVirtualCurrencyRequest;
    
    return Proxy;
}

void UPFServerAddUserVirtualCurrency::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if(ServerAPI.IsValid())
    {
        CallResult = ServerAPI->AddUserVirtualCurrency(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFServerAddUserVirtualCurrency::OnSuccessCallback(const PlayFab::ServerModels::FModifyUserVirtualCurrencyResult& Result)
{
    FBPServerModifyUserVirtualCurrencyResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
