// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerGetPlayerStatisticVersions.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerGetPlayerStatisticVersions::UPFServerGetPlayerStatisticVersions(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FGetPlayerStatisticVersionsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerGetPlayerStatisticVersions* UPFServerGetPlayerStatisticVersions::GetPlayerStatisticVersions(class APlayerController* PlayerController, const FBPServerGetPlayerStatisticVersionsRequest& InGetPlayerStatisticVersionsRequest)
{
    UPFServerGetPlayerStatisticVersions* Proxy = NewObject<UPFServerGetPlayerStatisticVersions>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetPlayerStatisticVersionsRequest;
    
    return Proxy;
}

void UPFServerGetPlayerStatisticVersions::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if(ServerAPI.IsValid())
    {
        CallResult = ServerAPI->GetPlayerStatisticVersions(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFServerGetPlayerStatisticVersions::OnSuccessCallback(const PlayFab::ServerModels::FGetPlayerStatisticVersionsResult& Result)
{
    FBPServerGetPlayerStatisticVersionsResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
