// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerAddPlayerTag.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerAddPlayerTag::UPFServerAddPlayerTag(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FAddPlayerTagDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerAddPlayerTag* UPFServerAddPlayerTag::AddPlayerTag(class APlayerController* PlayerController, const FBPServerAddPlayerTagRequest& InAddPlayerTagRequest)
{
    UPFServerAddPlayerTag* Proxy = NewObject<UPFServerAddPlayerTag>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InAddPlayerTagRequest;
    
    return Proxy;
}

void UPFServerAddPlayerTag::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if(ServerAPI.IsValid())
    {
        CallResult = ServerAPI->AddPlayerTag(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFServerAddPlayerTag::OnSuccessCallback(const PlayFab::ServerModels::FAddPlayerTagResult& Result)
{
    OnSuccess.Broadcast();
}
