// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerUpdateBans.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerUpdateBans::UPFServerUpdateBans(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FUpdateBansDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerUpdateBans* UPFServerUpdateBans::UpdateBans(class APlayerController* PlayerController, const FBPServerUpdateBansRequest& InUpdateBansRequest)
{
    UPFServerUpdateBans* Proxy = NewObject<UPFServerUpdateBans>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InUpdateBansRequest;
    
    return Proxy;
}

void UPFServerUpdateBans::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if(ServerAPI.IsValid())
    {
        CallResult = ServerAPI->UpdateBans(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFServerUpdateBans::OnSuccessCallback(const PlayFab::ServerModels::FUpdateBansResult& Result)
{
    FBPServerUpdateBansResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
