// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerUpdateCharacterStatistics.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerUpdateCharacterStatistics::UPFServerUpdateCharacterStatistics(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FUpdateCharacterStatisticsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerUpdateCharacterStatistics* UPFServerUpdateCharacterStatistics::UpdateCharacterStatistics(class APlayerController* PlayerController, const FBPServerUpdateCharacterStatisticsRequest& InUpdateCharacterStatisticsRequest)
{
    UPFServerUpdateCharacterStatistics* Proxy = NewObject<UPFServerUpdateCharacterStatistics>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InUpdateCharacterStatisticsRequest;
    
    return Proxy;
}

void UPFServerUpdateCharacterStatistics::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if(ServerAPI.IsValid())
    {
        CallResult = ServerAPI->UpdateCharacterStatistics(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFServerUpdateCharacterStatistics::OnSuccessCallback(const PlayFab::ServerModels::FUpdateCharacterStatisticsResult& Result)
{
    OnSuccess.Broadcast();
}
