// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerGrantItemsToCharacter.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerGrantItemsToCharacter::UPFServerGrantItemsToCharacter(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FGrantItemsToCharacterDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerGrantItemsToCharacter* UPFServerGrantItemsToCharacter::GrantItemsToCharacter(class APlayerController* PlayerController, const FBPServerGrantItemsToCharacterRequest& InGrantItemsToCharacterRequest)
{
    UPFServerGrantItemsToCharacter* Proxy = NewObject<UPFServerGrantItemsToCharacter>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGrantItemsToCharacterRequest;
    
    return Proxy;
}

void UPFServerGrantItemsToCharacter::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if(ServerAPI.IsValid())
    {
        CallResult = ServerAPI->GrantItemsToCharacter(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFServerGrantItemsToCharacter::OnSuccessCallback(const PlayFab::ServerModels::FGrantItemsToCharacterResult& Result)
{
    FBPServerGrantItemsToCharacterResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
