// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerGetPlayerProfile.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerGetPlayerProfile::UPFServerGetPlayerProfile(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FGetPlayerProfileDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerGetPlayerProfile* UPFServerGetPlayerProfile::GetPlayerProfile(class APlayerController* PlayerController, const FBPServerGetPlayerProfileRequest& InGetPlayerProfileRequest)
{
    UPFServerGetPlayerProfile* Proxy = NewObject<UPFServerGetPlayerProfile>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetPlayerProfileRequest;
    
    return Proxy;
}

void UPFServerGetPlayerProfile::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if (ServerAPI.IsValid())
    {
        CallResult = ServerAPI->GetPlayerProfile(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFServerGetPlayerProfile::OnSuccessCallback(const PlayFab::ServerModels::FGetPlayerProfileResult& Result)
{
    FBPServerGetPlayerProfileResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
