// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerGetLeaderboardAroundCharacter.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerGetLeaderboardAroundCharacter::UPFServerGetLeaderboardAroundCharacter(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FGetLeaderboardAroundCharacterDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerGetLeaderboardAroundCharacter* UPFServerGetLeaderboardAroundCharacter::GetLeaderboardAroundCharacter(class APlayerController* PlayerController, const FBPServerGetLeaderboardAroundCharacterRequest& InGetLeaderboardAroundCharacterRequest)
{
    UPFServerGetLeaderboardAroundCharacter* Proxy = NewObject<UPFServerGetLeaderboardAroundCharacter>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetLeaderboardAroundCharacterRequest;
    
    return Proxy;
}

void UPFServerGetLeaderboardAroundCharacter::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if(ServerAPI.IsValid())
    {
        CallResult = ServerAPI->GetLeaderboardAroundCharacter(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFServerGetLeaderboardAroundCharacter::OnSuccessCallback(const PlayFab::ServerModels::FGetLeaderboardAroundCharacterResult& Result)
{
    FBPServerGetLeaderboardAroundCharacterResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
