// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerGetCharacterInventory.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerGetCharacterInventory::UPFServerGetCharacterInventory(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FGetCharacterInventoryDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerGetCharacterInventory* UPFServerGetCharacterInventory::GetCharacterInventory(class APlayerController* PlayerController, const FBPServerGetCharacterInventoryRequest& InGetCharacterInventoryRequest)
{
    UPFServerGetCharacterInventory* Proxy = NewObject<UPFServerGetCharacterInventory>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetCharacterInventoryRequest;
    
    return Proxy;
}

void UPFServerGetCharacterInventory::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if (ServerAPI.IsValid())
    {
        CallResult = ServerAPI->GetCharacterInventory(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFServerGetCharacterInventory::OnSuccessCallback(const PlayFab::ServerModels::FGetCharacterInventoryResult& Result)
{
    FBPServerGetCharacterInventoryResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
