// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerRemoveFriend.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerRemoveFriend::UPFServerRemoveFriend(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FRemoveFriendDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerRemoveFriend* UPFServerRemoveFriend::RemoveFriend(class APlayerController* PlayerController, const FBPServerRemoveFriendRequest& InRemoveFriendRequest)
{
    UPFServerRemoveFriend* Proxy = NewObject<UPFServerRemoveFriend>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InRemoveFriendRequest;
    
    return Proxy;
}

void UPFServerRemoveFriend::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if(ServerAPI.IsValid())
    {
        CallResult = ServerAPI->RemoveFriend(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFServerRemoveFriend::OnSuccessCallback(const PlayFab::ServerModels::FEmptyResult& Result)
{
    OnSuccess.Broadcast();
}
