// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#include "PlayFabProxyPrivatePCH.h"
#include "PlayFab.h"
#include "PFAdminCreatePlayerSharedSecret.h"

UPFAdminCreatePlayerSharedSecret::UPFAdminCreatePlayerSharedSecret(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, SuccessDelegate(PlayFab::UPlayFabAdminAPI::FCreatePlayerSharedSecretDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
	, ErrorDelegate(PlayFab::FPlayFabErrorDelegate::CreateUObject(this, &ThisClass::OnErrorCallback))
{
}

UPFAdminCreatePlayerSharedSecret* UPFAdminCreatePlayerSharedSecret::CreatePlayerSharedSecret(UObject* WorldContextObject, class APlayerController* PlayerController , const FString& InFriendlyName)
{
	UPFAdminCreatePlayerSharedSecret* Proxy = NewObject<UPFAdminCreatePlayerSharedSecret>();
 	//Proxy->PlayerControllerWeakPtr = PlayerController;
	Proxy->Request.FriendlyName = InFriendlyName;
	

 	//Proxy->WorldContextObject = WorldContextObject;
	return Proxy;
}

void UPFAdminCreatePlayerSharedSecret::Activate()
{
	// grab the module, so we can get a valid pointer to the client API 
	PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

	bool CallResult = false;

	if(AdminAPI.IsValid())
	{	
		CallResult = AdminAPI->CreatePlayerSharedSecret(Request, SuccessDelegate, ErrorDelegate);
	}

	if(CallResult == false)
	{
		FBPAdminCreatePlayerSharedSecretResult BPResult;
 		OnFailure.Broadcast(BPResult);
	}
}


//////////////////////////////////////////////////////////////////////////
// Delegate handles
void UPFAdminCreatePlayerSharedSecret::OnSuccessCallback(const PlayFab::AdminModels::FCreatePlayerSharedSecretResult& Result)
{
	FBPAdminCreatePlayerSharedSecretResult BPResult;
 	BPResult.Data = Result;
 	OnSuccess.Broadcast(BPResult);
}

void UPFAdminCreatePlayerSharedSecret::OnErrorCallback(const PlayFab::FPlayFabError& InError)
{
	FBPAdminCreatePlayerSharedSecretResult BPResult;
 	OnFailure.Broadcast(BPResult);	
}
