// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFMatchmakerUserInfo.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFMatchmakerUserInfo::UPFMatchmakerUserInfo(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabMatchmakerAPI::FUserInfoDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFMatchmakerUserInfo* UPFMatchmakerUserInfo::UserInfo(class APlayerController* PlayerController, const FBPMatchmakerUserInfoRequest& InUserInfoRequest)
{
    UPFMatchmakerUserInfo* Proxy = NewObject<UPFMatchmakerUserInfo>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InUserInfoRequest;
    
    return Proxy;
}

void UPFMatchmakerUserInfo::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabMatchmakerPtr MatchmakerAPI = IPlayFabModuleInterface::Get().GetMatchmakerAPI();

    bool CallResult = false;

    if (MatchmakerAPI.IsValid())
    {
        CallResult = MatchmakerAPI->UserInfo(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFMatchmakerUserInfo::OnSuccessCallback(const PlayFab::MatchmakerModels::FUserInfoResponse& Result)
{
    FBPMatchmakerUserInfoResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
