// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerUpdateAvatarUrl.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFServerUpdateAvatarUrl : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnSuccess; 

	UPROPERTY(BlueprintAssignable)
	FEmptyOnlineDelegate OnFailure; 
	
	// Update the avatar URL of the specified player
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Server|Account Management")
	static UPFServerUpdateAvatarUrl* UpdateAvatarUrl(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InPlayFabId, const FString& InImageUrl);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ServerModels::FUpdateAvatarUrlRequest Request;

	PlayFab::UPlayFabServerAPI::FUpdateAvatarUrlDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ServerModels::FEmptyResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
