// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminGetCloudScriptVersions.generated.h"

UCLASS(MinimalAPI)
class UPFAdminGetCloudScriptVersions : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPAdminGetCloudScriptVersionsResultDelegate OnSuccess;

    // Lists all the current cloud script versions. For each version, information about the current published and latest revisions is also listed.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Server-Side Cloud Script")
        static UPFAdminGetCloudScriptVersions* GetCloudScriptVersions(class APlayerController* PlayerController);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    
    PlayFab::UPlayFabAdminAPI::FGetCloudScriptVersionsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FGetCloudScriptVersionsResult& Result);
};
