// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminUpdateUserPublisherData.generated.h"

UCLASS(MinimalAPI)
class UPFAdminUpdateUserPublisherData : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPAdminUpdateUserDataResultDelegate OnSuccess;

    // Updates the publisher-specific custom data for the user which is readable and writable by the client
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Player Data Management")
        static UPFAdminUpdateUserPublisherData* UpdateUserPublisherData(class APlayerController* PlayerController, const FBPAdminUpdateUserDataRequest& InUpdateUserDataRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPAdminUpdateUserDataRequest Request;
    PlayFab::UPlayFabAdminAPI::FUpdateUserPublisherDataDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FUpdateUserDataResult& Result);
};
