// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminGetPlayerStatisticDefinitions.generated.h"

UCLASS(MinimalAPI)
class UPFAdminGetPlayerStatisticDefinitions : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPAdminGetPlayerStatisticDefinitionsResultDelegate OnSuccess;

    // Retrieves the configuration information for all player statistics defined in the title, regardless of whether they have a reset interval.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Player Data Management")
        static UPFAdminGetPlayerStatisticDefinitions* GetPlayerStatisticDefinitions(class APlayerController* PlayerController);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    
    PlayFab::UPlayFabAdminAPI::FGetPlayerStatisticDefinitionsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FGetPlayerStatisticDefinitionsResult& Result);
};
