// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminGetUserInventory.generated.h"

UCLASS(MinimalAPI)
class UPFAdminGetUserInventory : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPAdminGetUserInventoryResultDelegate OnSuccess;

    // Retrieves the specified user's current inventory of virtual goods
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Player Item Management")
        static UPFAdminGetUserInventory* GetUserInventory(class APlayerController* PlayerController, const FBPAdminGetUserInventoryRequest& InGetUserInventoryRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPAdminGetUserInventoryRequest Request;
    PlayFab::UPlayFabAdminAPI::FGetUserInventoryDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FGetUserInventoryResult& Result);
};
