// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminAddUserVirtualCurrency.generated.h"

UCLASS(MinimalAPI)
class UPFAdminAddUserVirtualCurrency : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPAdminModifyUserVirtualCurrencyResultDelegate OnSuccess;

    // Increments the specified virtual currency by the stated amount
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Player Item Management")
        static UPFAdminAddUserVirtualCurrency* AddUserVirtualCurrency(class APlayerController* PlayerController, const FBPAdminAddUserVirtualCurrencyRequest& InAddUserVirtualCurrencyRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPAdminAddUserVirtualCurrencyRequest Request;
    PlayFab::UPlayFabAdminAPI::FAddUserVirtualCurrencyDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FModifyUserVirtualCurrencyResult& Result);
};
