// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminUpdateUserPublisherInternalData.generated.h"

UCLASS(MinimalAPI)
class UPFAdminUpdateUserPublisherInternalData : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPAdminUpdateUserDataResultDelegate OnSuccess;

    // Updates the publisher-specific custom data for the user which cannot be accessed by the client
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Player Data Management")
        static UPFAdminUpdateUserPublisherInternalData* UpdateUserPublisherInternalData(class APlayerController* PlayerController, const FBPAdminUpdateUserInternalDataRequest& InUpdateUserInternalDataRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPAdminUpdateUserInternalDataRequest Request;
    PlayFab::UPlayFabAdminAPI::FUpdateUserPublisherInternalDataDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FUpdateUserDataResult& Result);
};
