// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminRevokeBans.generated.h"

UCLASS(MinimalAPI)
class UPFAdminRevokeBans : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPAdminRevokeBansResultDelegate OnSuccess;

    // Revoke all active bans specified with BanId.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Account Management")
        static UPFAdminRevokeBans* RevokeBans(class APlayerController* PlayerController, const FBPAdminRevokeBansRequest& InRevokeBansRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPAdminRevokeBansRequest Request;
    PlayFab::UPlayFabAdminAPI::FRevokeBansDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FRevokeBansResult& Result);
};
