// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabMatchmakerAPI.h"
#include "Core/PlayFabMatchmakerDataModels.h"
#include "Proxy/PlayFabMatchmakerBPDataModels.h"
#include "PFMatchmakerAuthUser.generated.h"

UCLASS(MinimalAPI)
class UPFMatchmakerAuthUser : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPMatchmakerAuthUserResponseDelegate OnSuccess;

    // Validates a user with the PlayFab service
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Matchmaker|Matchmaking")
        static UPFMatchmakerAuthUser* AuthUser(class APlayerController* PlayerController, const FBPMatchmakerAuthUserRequest& InAuthUserRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPMatchmakerAuthUserRequest Request;
    PlayFab::UPlayFabMatchmakerAPI::FAuthUserDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::MatchmakerModels::FAuthUserResponse& Result);
};
