// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabMatchmakerAPI.h"
#include "Core/PlayFabMatchmakerDataModels.h"
#include "Proxy/PlayFabMatchmakerBPDataModels.h"
#include "PFMatchmakerPlayerLeft.generated.h"

UCLASS(MinimalAPI)
class UPFMatchmakerPlayerLeft : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Informs the PlayFab game server hosting service that the indicated user has left the Game Server Instance specified
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Matchmaker|Matchmaking")
        static UPFMatchmakerPlayerLeft* PlayerLeft(class APlayerController* PlayerController, const FBPMatchmakerPlayerLeftRequest& InPlayerLeftRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPMatchmakerPlayerLeftRequest Request;
    PlayFab::UPlayFabMatchmakerAPI::FPlayerLeftDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::MatchmakerModels::FPlayerLeftResponse& Result);
};
