// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientRemoveFriend.generated.h"

UCLASS(MinimalAPI)
class UPFClientRemoveFriend : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Removes a specified user from the friend list of the local user
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Friend List Management")
        static UPFClientRemoveFriend* RemoveFriend(class APlayerController* PlayerController, const FBPClientRemoveFriendRequest& InRemoveFriendRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientRemoveFriendRequest Request;
    PlayFab::UPlayFabClientAPI::FRemoveFriendDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FRemoveFriendResult& Result);
};
