// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientLinkGameCenterAccount.generated.h"

UCLASS(MinimalAPI)
class UPFClientLinkGameCenterAccount : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Links the Game Center account associated with the provided Game Center ID to the user's PlayFab account
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Account Management")
        static UPFClientLinkGameCenterAccount* LinkGameCenterAccount(class APlayerController* PlayerController, const FBPClientLinkGameCenterAccountRequest& InLinkGameCenterAccountRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientLinkGameCenterAccountRequest Request;
    PlayFab::UPlayFabClientAPI::FLinkGameCenterAccountDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FLinkGameCenterAccountResult& Result);
};
