// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientRegisterPlayFabUser.generated.h"

UCLASS(MinimalAPI)
class UPFClientRegisterPlayFabUser : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientRegisterPlayFabUserResultDelegate OnSuccess;

    // Registers a new Playfab user account, returning a session identifier that can subsequently be used for API calls which require an authenticated user. You must supply either a username or an email address.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Authentication")
        static UPFClientRegisterPlayFabUser* RegisterPlayFabUser(class APlayerController* PlayerController, const FBPClientRegisterPlayFabUserRequest& InRegisterPlayFabUserRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientRegisterPlayFabUserRequest Request;
    PlayFab::UPlayFabClientAPI::FRegisterPlayFabUserDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FRegisterPlayFabUserResult& Result);
};
