// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientOpenTrade.generated.h"

UCLASS(MinimalAPI)
class UPFClientOpenTrade : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientOpenTradeResponseDelegate OnSuccess;

    // Opens a new outstanding trade. Note that a given item instance may only be in one open trade at a time.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Trading")
        static UPFClientOpenTrade* OpenTrade(class APlayerController* PlayerController, const FBPClientOpenTradeRequest& InOpenTradeRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientOpenTradeRequest Request;
    PlayFab::UPlayFabClientAPI::FOpenTradeDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FOpenTradeResponse& Result);
};
