// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetFriendsList.generated.h"

UCLASS(MinimalAPI)
class UPFClientGetFriendsList : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientGetFriendsListResultDelegate OnSuccess;

    // Retrieves the current friend list for the local user, constrained to users who have PlayFab accounts. Friends from linked accounts (Facebook, Steam) are also included. You may optionally exclude some linked services' friends.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Friend List Management")
        static UPFClientGetFriendsList* GetFriendsList(class APlayerController* PlayerController, const FBPClientGetFriendsListRequest& InGetFriendsListRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientGetFriendsListRequest Request;
    PlayFab::UPlayFabClientAPI::FGetFriendsListDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FGetFriendsListResult& Result);
};
