// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientRegisterForIOSPushNotification.generated.h"

UCLASS(MinimalAPI)
class UPFClientRegisterForIOSPushNotification : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Registers the iOS device to receive push notifications
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Platform Specific Methods")
        static UPFClientRegisterForIOSPushNotification* RegisterForIOSPushNotification(class APlayerController* PlayerController, const FBPClientRegisterForIOSPushNotificationRequest& InRegisterForIOSPushNotificationRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientRegisterForIOSPushNotificationRequest Request;
    PlayFab::UPlayFabClientAPI::FRegisterForIOSPushNotificationDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FRegisterForIOSPushNotificationResult& Result);
};
