// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientAndroidDevicePushNotificationRegistration.generated.h"

UCLASS(MinimalAPI)
class UPFClientAndroidDevicePushNotificationRegistration : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Registers the Android device to receive push notifications
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Platform Specific Methods")
        static UPFClientAndroidDevicePushNotificationRegistration* AndroidDevicePushNotificationRegistration(class APlayerController* PlayerController, const FBPClientAndroidDevicePushNotificationRegistrationRequest& InAndroidDevicePushNotificationRegistrationRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientAndroidDevicePushNotificationRegistrationRequest Request;
    PlayFab::UPlayFabClientAPI::FAndroidDevicePushNotificationRegistrationDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FAndroidDevicePushNotificationRegistrationResult& Result);
};
