// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientUnlinkGameCenterAccount.generated.h"

UCLASS(MinimalAPI)
class UPFClientUnlinkGameCenterAccount : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Unlinks the related Game Center account from the user's PlayFab account
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Account Management")
        static UPFClientUnlinkGameCenterAccount* UnlinkGameCenterAccount(class APlayerController* PlayerController);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    
    PlayFab::UPlayFabClientAPI::FUnlinkGameCenterAccountDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FUnlinkGameCenterAccountResult& Result);
};
