// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetUserReadOnlyData.generated.h"

UCLASS(MinimalAPI)
class UPFClientGetUserReadOnlyData : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientGetUserDataResultDelegate OnSuccess;

    // Retrieves the title-specific custom data for the user which can only be read by the client
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Player Data Management")
        static UPFClientGetUserReadOnlyData* GetUserReadOnlyData(class APlayerController* PlayerController, const FBPClientGetUserDataRequest& InGetUserDataRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientGetUserDataRequest Request;
    PlayFab::UPlayFabClientAPI::FGetUserReadOnlyDataDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FGetUserDataResult& Result);
};
