// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetCharacterData.generated.h"

UCLASS(MinimalAPI)
class UPFClientGetCharacterData : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientGetCharacterDataResultDelegate OnSuccess;

    // Retrieves the title-specific custom data for the character which is readable and writable by the client
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Character Data")
        static UPFClientGetCharacterData* GetCharacterData(class APlayerController* PlayerController, const FBPClientGetCharacterDataRequest& InGetCharacterDataRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientGetCharacterDataRequest Request;
    PlayFab::UPlayFabClientAPI::FGetCharacterDataDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FGetCharacterDataResult& Result);
};
