// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientUnlockContainerItem.generated.h"

UCLASS(MinimalAPI)
class UPFClientUnlockContainerItem : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientUnlockContainerItemResultDelegate OnSuccess;

    // Searches target inventory for an ItemInstance matching the given CatalogItemId, if necessary unlocks it using an appropriate key, and returns the contents of the opened container. If the container (and key when relevant) are consumable (RemainingUses > 0), their RemainingUses will be decremented, consistent with the operation of ConsumeItem.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Player Item Management")
        static UPFClientUnlockContainerItem* UnlockContainerItem(class APlayerController* PlayerController, const FBPClientUnlockContainerItemRequest& InUnlockContainerItemRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientUnlockContainerItemRequest Request;
    PlayFab::UPlayFabClientAPI::FUnlockContainerItemDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FUnlockContainerItemResult& Result);
};
