// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientUnlockContainerInstance.generated.h"

UCLASS(MinimalAPI)
class UPFClientUnlockContainerInstance : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPClientUnlockContainerItemResultDelegate OnSuccess;

    // Opens the specified container, with the specified key (when required), and returns the contents of the opened container. If the container (and key when relevant) are consumable (RemainingUses > 0), their RemainingUses will be decremented, consistent with the operation of ConsumeItem.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Client|Player Item Management")
        static UPFClientUnlockContainerInstance* UnlockContainerInstance(class APlayerController* PlayerController, const FBPClientUnlockContainerInstanceRequest& InUnlockContainerInstanceRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPClientUnlockContainerInstanceRequest Request;
    PlayFab::UPlayFabClientAPI::FUnlockContainerInstanceDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ClientModels::FUnlockContainerItemResult& Result);
};
