// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminSetPublisherData.generated.h"

UCLASS(MinimalAPI)
class UPFAdminSetPublisherData : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Updates the key-value store of custom publisher settings
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Shared Group Data")
        static UPFAdminSetPublisherData* SetPublisherData(class APlayerController* PlayerController, const FBPAdminSetPublisherDataRequest& InSetPublisherDataRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPAdminSetPublisherDataRequest Request;
    PlayFab::UPlayFabAdminAPI::FSetPublisherDataDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FSetPublisherDataResult& Result);
};
