// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminSetPlayerSecret.generated.h"

UCLASS(MinimalAPI)
class UPFAdminSetPlayerSecret : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Sets or resets the player's secret. Player secrets are used to sign API requests.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Authentication")
        static UPFAdminSetPlayerSecret* SetPlayerSecret(class APlayerController* PlayerController, const FBPAdminSetPlayerSecretRequest& InSetPlayerSecretRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPAdminSetPlayerSecretRequest Request;
    PlayFab::UPlayFabAdminAPI::FSetPlayerSecretDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FSetPlayerSecretResult& Result);
};
