// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminUpdateTask.generated.h"

UCLASS(MinimalAPI)
class UPFAdminUpdateTask : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Update an existing task.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|ScheduledTask")
        static UPFAdminUpdateTask* UpdateTask(class APlayerController* PlayerController, const FBPAdminUpdateTaskRequest& InUpdateTaskRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPAdminUpdateTaskRequest Request;
    PlayFab::UPlayFabAdminAPI::FUpdateTaskDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FEmptyResult& Result);
};
