// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminListServerBuilds.generated.h"

UCLASS(MinimalAPI)
class UPFAdminListServerBuilds : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPAdminListBuildsResultDelegate OnSuccess;

    // Retrieves the build details for all game server executables which are currently defined for the title
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Custom Server Management")
        static UPFAdminListServerBuilds* ListServerBuilds(class APlayerController* PlayerController);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    
    PlayFab::UPlayFabAdminAPI::FListServerBuildsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FListBuildsResult& Result);
};
