// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminResetUserStatistics.generated.h"

UCLASS(MinimalAPI)
class UPFAdminResetUserStatistics : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Completely removes all statistics for the specified user, for the current game
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Player Data Management")
        static UPFAdminResetUserStatistics* ResetUserStatistics(class APlayerController* PlayerController, const FBPAdminResetUserStatisticsRequest& InResetUserStatisticsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPAdminResetUserStatisticsRequest Request;
    PlayFab::UPlayFabAdminAPI::FResetUserStatisticsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FResetUserStatisticsResult& Result);
};
