// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminResetCharacterStatistics.generated.h"

UCLASS(MinimalAPI)
class UPFAdminResetCharacterStatistics : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Completely removes all statistics for the specified character, for the current game
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Characters")
        static UPFAdminResetCharacterStatistics* ResetCharacterStatistics(class APlayerController* PlayerController, const FBPAdminResetCharacterStatisticsRequest& InResetCharacterStatisticsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPAdminResetCharacterStatisticsRequest Request;
    PlayFab::UPlayFabAdminAPI::FResetCharacterStatisticsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FResetCharacterStatisticsResult& Result);
};
