// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once
#include "OnlineBlueprintCallProxyBase.h"

#include "Core/PlayFabClientAPI.h"
#include "Core/PlayFabClientDataModels.h"
#include "Proxy/PlayFabClientBPDataModels.h"
#include "PFClientGetPlayerProfile.generated.h"

UCLASS()
class PLAYFABPROXY_API UPFClientGetPlayerProfile : public UOnlineBlueprintCallProxyBase
{
	GENERATED_UCLASS_BODY()
public:

	UPROPERTY(BlueprintAssignable)
	FBPClientGetPlayerProfileResultDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FBPClientGetPlayerProfileResultDelegate OnFailure;
	
	// Retrieves the player's profile
	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject"), Category = "PlayFab|Client|Account Management")
	static UPFClientGetPlayerProfile* GetPlayerProfile(UObject* WorldContextObject, class APlayerController* PlayerController, const FString& InPlayFabId, const FBPClientPlayerProfileViewConstraints& InProfileConstraints);

	// UOnlineBlueprintCallProxyBase interface
	virtual void Activate() override;
	// End of UOnlineBlueprintCallProxyBase interface

private:

	PlayFab::ClientModels::FGetPlayerProfileRequest Request;

	PlayFab::UPlayFabClientAPI::FGetPlayerProfileDelegate	SuccessDelegate;
	PlayFab::FPlayFabErrorDelegate							ErrorDelegate;

	void OnSuccessCallback(const PlayFab::ClientModels::FGetPlayerProfileResult& Result);
	void OnErrorCallback(const PlayFab::FPlayFabError& Error);
};
