// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerRemovePlayerTag.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerRemovePlayerTag::UPFServerRemovePlayerTag(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FRemovePlayerTagDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerRemovePlayerTag* UPFServerRemovePlayerTag::RemovePlayerTag(class APlayerController* PlayerController, const FBPServerRemovePlayerTagRequest& InRemovePlayerTagRequest)
{
    UPFServerRemovePlayerTag* Proxy = NewObject<UPFServerRemovePlayerTag>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InRemovePlayerTagRequest;
    
    return Proxy;
}

void UPFServerRemovePlayerTag::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if (ServerAPI.IsValid())
    {
        CallResult = ServerAPI->RemovePlayerTag(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFServerRemovePlayerTag::OnSuccessCallback(const PlayFab::ServerModels::FRemovePlayerTagResult& Result)
{
    OnSuccess.Broadcast();
}
