// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerGetPlayerTags.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerGetPlayerTags::UPFServerGetPlayerTags(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FGetPlayerTagsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerGetPlayerTags* UPFServerGetPlayerTags::GetPlayerTags(class APlayerController* PlayerController, const FBPServerGetPlayerTagsRequest& InGetPlayerTagsRequest)
{
    UPFServerGetPlayerTags* Proxy = NewObject<UPFServerGetPlayerTags>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetPlayerTagsRequest;
    
    return Proxy;
}

void UPFServerGetPlayerTags::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if (ServerAPI.IsValid())
    {
        CallResult = ServerAPI->GetPlayerTags(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFServerGetPlayerTags::OnSuccessCallback(const PlayFab::ServerModels::FGetPlayerTagsResult& Result)
{
    FBPServerGetPlayerTagsResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
