// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerRegisterGame.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerRegisterGame::UPFServerRegisterGame(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FRegisterGameDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerRegisterGame* UPFServerRegisterGame::RegisterGame(class APlayerController* PlayerController, const FBPServerRegisterGameRequest& InRegisterGameRequest)
{
    UPFServerRegisterGame* Proxy = NewObject<UPFServerRegisterGame>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InRegisterGameRequest;
    
    return Proxy;
}

void UPFServerRegisterGame::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if(ServerAPI.IsValid())
    {
        CallResult = ServerAPI->RegisterGame(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if(CallResult == false)
    {
        OnFailure.Broadcast();
    }
}

void UPFServerRegisterGame::OnSuccessCallback(const PlayFab::ServerModels::FRegisterGameResponse& Result)
{
    FBPServerRegisterGameResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
