// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerUpdateUserReadOnlyData.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerUpdateUserReadOnlyData::UPFServerUpdateUserReadOnlyData(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FUpdateUserReadOnlyDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerUpdateUserReadOnlyData* UPFServerUpdateUserReadOnlyData::UpdateUserReadOnlyData(class APlayerController* PlayerController, const FBPServerUpdateUserDataRequest& InUpdateUserDataRequest)
{
    UPFServerUpdateUserReadOnlyData* Proxy = NewObject<UPFServerUpdateUserReadOnlyData>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InUpdateUserDataRequest;
    
    return Proxy;
}

void UPFServerUpdateUserReadOnlyData::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if (ServerAPI.IsValid())
    {
        CallResult = ServerAPI->UpdateUserReadOnlyData(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFServerUpdateUserReadOnlyData::OnSuccessCallback(const PlayFab::ServerModels::FUpdateUserDataResult& Result)
{
    FBPServerUpdateUserDataResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
